# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stretcher_pwr_ctrl_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PowerControlDialog(object):
    def setupUi(self, PowerControlDialog):
        PowerControlDialog.setObjectName("PowerControlDialog")
        PowerControlDialog.resize(800, 500)
        self.sinusoidalButton = QtWidgets.QPushButton(PowerControlDialog)
        self.sinusoidalButton.setGeometry(QtCore.QRect(20, 360, 100, 100))
        self.sinusoidalButton.setMinimumSize(QtCore.QSize(100, 100))
        self.sinusoidalButton.setStyleSheet("background-image: url(:/buttons/resources/Sinus.png);\n"
"background-color: rgb(240, 238, 126);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.sinusoidalButton.setText("")
        self.sinusoidalButton.setObjectName("sinusoidalButton")
        self.triangularButton = QtWidgets.QPushButton(PowerControlDialog)
        self.triangularButton.setGeometry(QtCore.QRect(20, 80, 100, 100))
        self.triangularButton.setMinimumSize(QtCore.QSize(100, 100))
        self.triangularButton.setStyleSheet("background-image: url(:/buttons/resources/Triangular.png);\n"
"background-color: rgb(248, 247, 190);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.triangularButton.setText("")
        self.triangularButton.setObjectName("triangularButton")
        self.squareButton = QtWidgets.QPushButton(PowerControlDialog)
        self.squareButton.setGeometry(QtCore.QRect(20, 220, 100, 100))
        self.squareButton.setMinimumSize(QtCore.QSize(100, 100))
        self.squareButton.setStyleSheet("background-image: url(:/buttons/resources/Cuadrada.png);\n"
"background-color: rgb(244, 243, 158);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.squareButton.setText("")
        self.squareButton.setObjectName("squareButton")
        self.layoutWidget = QtWidgets.QWidget(PowerControlDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 60, 101, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.powerUpButton = QtWidgets.QPushButton(self.layoutWidget)
        self.powerUpButton.setMinimumSize(QtCore.QSize(50, 50))
        self.powerUpButton.setStyleSheet("background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerUpButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/resources/Arriba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.powerUpButton.setIcon(icon)
        self.powerUpButton.setObjectName("powerUpButton")
        self.verticalLayout.addWidget(self.powerUpButton)
        self.powerDwnButton = QtWidgets.QPushButton(self.layoutWidget)
        self.powerDwnButton.setMinimumSize(QtCore.QSize(50, 50))
        self.powerDwnButton.setStyleSheet("background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerDwnButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/resources/Abajo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.powerDwnButton.setIcon(icon1)
        self.powerDwnButton.setObjectName("powerDwnButton")
        self.verticalLayout.addWidget(self.powerDwnButton)
        self.layoutWidget_2 = QtWidgets.QWidget(PowerControlDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(230, 190, 102, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.powerUpButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.powerUpButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.powerUpButton_2.setStyleSheet("background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerUpButton_2.setText("")
        self.powerUpButton_2.setIcon(icon)
        self.powerUpButton_2.setObjectName("powerUpButton_2")
        self.verticalLayout_2.addWidget(self.powerUpButton_2)
        self.powerDwnButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.powerDwnButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.powerDwnButton_2.setStyleSheet("background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerDwnButton_2.setText("")
        self.powerDwnButton_2.setIcon(icon1)
        self.powerDwnButton_2.setObjectName("powerDwnButton_2")
        self.verticalLayout_2.addWidget(self.powerDwnButton_2)
        self.layoutWidget_3 = QtWidgets.QWidget(PowerControlDialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(230, 340, 102, 131))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.powerUpButton_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.powerUpButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.powerUpButton_3.setStyleSheet("background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerUpButton_3.setText("")
        self.powerUpButton_3.setIcon(icon)
        self.powerUpButton_3.setObjectName("powerUpButton_3")
        self.verticalLayout_3.addWidget(self.powerUpButton_3)
        self.powerDwnButton_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.powerDwnButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.powerDwnButton_3.setStyleSheet("background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerDwnButton_3.setText("")
        self.powerDwnButton_3.setIcon(icon1)
        self.powerDwnButton_3.setObjectName("powerDwnButton_3")
        self.verticalLayout_3.addWidget(self.powerDwnButton_3)
        self.label = QtWidgets.QLabel(PowerControlDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PowerControlDialog)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PowerControlDialog)
        self.label_3.setGeometry(QtCore.QRect(140, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PowerControlDialog)
        self.label_4.setGeometry(QtCore.QRect(140, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(PowerControlDialog)
        self.label_5.setGeometry(QtCore.QRect(390, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(PowerControlDialog)
        self.label_6.setGeometry(QtCore.QRect(380, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(PowerControlDialog)
        self.label_7.setGeometry(QtCore.QRect(390, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(PowerControlDialog)
        self.label_8.setGeometry(QtCore.QRect(390, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(PowerControlDialog)
        self.label_9.setGeometry(QtCore.QRect(390, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(PowerControlDialog)
        self.label_10.setGeometry(QtCore.QRect(510, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(PowerControlDialog)
        self.label_11.setGeometry(QtCore.QRect(510, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(PowerControlDialog)
        self.label_12.setGeometry(QtCore.QRect(500, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(PowerControlDialog)
        self.label_13.setGeometry(QtCore.QRect(510, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(PowerControlDialog)
        self.label_14.setGeometry(QtCore.QRect(640, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(PowerControlDialog)
        self.label_15.setGeometry(QtCore.QRect(640, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(PowerControlDialog)
        self.label_16.setGeometry(QtCore.QRect(630, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(PowerControlDialog)
        self.label_17.setGeometry(QtCore.QRect(640, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.doneButton = QtWidgets.QPushButton(PowerControlDialog)
        self.doneButton.setGeometry(QtCore.QRect(410, 451, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doneButton.setFont(font)
        self.doneButton.setObjectName("doneButton")

        self.retranslateUi(PowerControlDialog)
        QtCore.QMetaObject.connectSlotsByName(PowerControlDialog)

    def retranslateUi(self, PowerControlDialog):
        _translate = QtCore.QCoreApplication.translate
        PowerControlDialog.setWindowTitle(_translate("PowerControlDialog", "Dialog"))
        self.label.setText(_translate("PowerControlDialog", "Power Limits for signals:"))
        self.label_2.setText(_translate("PowerControlDialog", "100%"))
        self.label_3.setText(_translate("PowerControlDialog", "100%"))
        self.label_4.setText(_translate("PowerControlDialog", "100%"))
        self.label_5.setText(_translate("PowerControlDialog", "Estimated Results:"))
        self.label_6.setText(_translate("PowerControlDialog", "Irms [A]:"))
        self.label_7.setText(_translate("PowerControlDialog", "100%"))
        self.label_8.setText(_translate("PowerControlDialog", "100%"))
        self.label_9.setText(_translate("PowerControlDialog", "100%"))
        self.label_10.setText(_translate("PowerControlDialog", "100%"))
        self.label_11.setText(_translate("PowerControlDialog", "100%"))
        self.label_12.setText(_translate("PowerControlDialog", "0.65mm"))
        self.label_13.setText(_translate("PowerControlDialog", "100%"))
        self.label_14.setText(_translate("PowerControlDialog", "100%"))
        self.label_15.setText(_translate("PowerControlDialog", "100%"))
        self.label_16.setText(_translate("PowerControlDialog", "0.80mm"))
        self.label_17.setText(_translate("PowerControlDialog", "100%"))
        self.doneButton.setText(_translate("PowerControlDialog", "Done!"))

import stretcher3_res_rc
