# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'light_ver_1_0.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 800)
        Dialog.setStyleSheet("QDialog {\n"
"background-image: url(:/background/resources/background_light_02.png);\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 300, 571, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(18)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pannelAButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pannelAButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pannelAButton.setFont(font)
        self.pannelAButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pannelAButton.setStyleSheet("background-color: rgb(225, 237, 247);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.pannelAButton.setObjectName("pannelAButton")
        self.horizontalLayout_2.addWidget(self.pannelAButton)
        self.pannelBButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pannelBButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pannelBButton.setFont(font)
        self.pannelBButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pannelBButton.setStyleSheet("background-color: rgb(189, 220, 245);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.pannelBButton.setObjectName("pannelBButton")
        self.horizontalLayout_2.addWidget(self.pannelBButton)
        self.pannelCButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pannelCButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pannelCButton.setFont(font)
        self.pannelCButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pannelCButton.setStyleSheet("background-color: rgb(149, 200, 240);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.pannelCButton.setObjectName("pannelCButton")
        self.horizontalLayout_2.addWidget(self.pannelCButton)
        self.pannelDButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pannelDButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pannelDButton.setFont(font)
        self.pannelDButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pannelDButton.setStyleSheet("background-color: rgb(107, 178, 237);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.pannelDButton.setObjectName("pannelDButton")
        self.horizontalLayout_2.addWidget(self.pannelDButton)
        self.pannelEButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pannelEButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pannelEButton.setFont(font)
        self.pannelEButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pannelEButton.setStyleSheet("background-color: rgb(32, 145, 235);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.pannelEButton.setObjectName("pannelEButton")
        self.horizontalLayout_2.addWidget(self.pannelEButton)
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(656, 344, 236, 241))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cwaveButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.cwaveButton.setMinimumSize(QtCore.QSize(100, 100))
        self.cwaveButton.setStyleSheet("background-image: url(:/buttons/resources/cwave_enable.png);\n"
"background-color: rgb(242, 248, 250);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.cwaveButton.setText("")
        self.cwaveButton.setObjectName("cwaveButton")
        self.verticalLayout_2.addWidget(self.cwaveButton)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.inphaseButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.inphaseButton.setMinimumSize(QtCore.QSize(100, 100))
        self.inphaseButton.setStyleSheet("background-image: url(:/buttons/resources/inphase_enable.png);\n"
"background-color: rgb(242, 248, 250);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.inphaseButton.setText("")
        self.inphaseButton.setObjectName("inphaseButton")
        self.horizontalLayout_9.addWidget(self.inphaseButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.outphaseButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.outphaseButton.setMinimumSize(QtCore.QSize(100, 100))
        self.outphaseButton.setStyleSheet("background-image: url(:/buttons/resources/outphase_enable.png);\n"
"background-color: rgb(242, 248, 250);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.outphaseButton.setText("")
        self.outphaseButton.setObjectName("outphaseButton")
        self.horizontalLayout_9.addWidget(self.outphaseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(940, 645, 300, 120))
        self.startButton.setMinimumSize(QtCore.QSize(100, 100))
        self.startButton.setStyleSheet("background-image: url(:/buttons/resources/Play.png);\n"
"background-color: rgb(245, 245, 245);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.startButton.setText("")
        self.startButton.setObjectName("startButton")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(42, 135, 456, 102))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(18)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min20Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.min20Button.setMinimumSize(QtCore.QSize(90, 90))
        self.min20Button.setStyleSheet("background-image: url(:/buttons/resources/20min.png);\n"
"background-color: rgb(247, 246, 225);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.min20Button.setText("")
        self.min20Button.setObjectName("min20Button")
        self.horizontalLayout.addWidget(self.min20Button)
        self.min30Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.min30Button.setMinimumSize(QtCore.QSize(90, 90))
        self.min30Button.setStyleSheet("background-image: url(:/buttons/resources/30min.png);\n"
"background-color: rgb(247, 246, 202);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.min30Button.setText("")
        self.min30Button.setObjectName("min30Button")
        self.horizontalLayout.addWidget(self.min30Button)
        self.min45Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.min45Button.setMinimumSize(QtCore.QSize(90, 90))
        self.min45Button.setStyleSheet("background-image: url(:/buttons/resources/45min.png);\n"
"background-color: rgb(247, 246, 180);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.min45Button.setText("")
        self.min45Button.setObjectName("min45Button")
        self.horizontalLayout.addWidget(self.min45Button)
        self.min60Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.min60Button.setMinimumSize(QtCore.QSize(90, 90))
        self.min60Button.setStyleSheet("background-image: url(:/buttons/resources/60min.png);\n"
"background-color: rgb(246, 245, 157);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.min60Button.setText("")
        self.min60Button.setObjectName("min60Button")
        self.horizontalLayout.addWidget(self.min60Button)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(935, 305, 102, 306))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mem1Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.mem1Button.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.mem1Button.setFont(font)
        self.mem1Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mem1Button.setStyleSheet("color: rgb(55, 52, 53);\n"
"background-color: rgb(255, 244, 230);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.mem1Button.setObjectName("mem1Button")
        self.verticalLayout_4.addWidget(self.mem1Button)
        self.mem2Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.mem2Button.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.mem2Button.setFont(font)
        self.mem2Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mem2Button.setStyleSheet("color: rgb(55, 52, 53);\n"
"background-color: rgb(255, 232, 204);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.mem2Button.setObjectName("mem2Button")
        self.verticalLayout_4.addWidget(self.mem2Button)
        self.mem3Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.mem3Button.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.mem3Button.setFont(font)
        self.mem3Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mem3Button.setStyleSheet("color: rgb(55, 52, 53);\n"
"background-color: rgb(255, 221, 179);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.mem3Button.setObjectName("mem3Button")
        self.verticalLayout_4.addWidget(self.mem3Button)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(1050, 310, 191, 296))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(28)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mem11Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem11Label.setFont(font)
        self.mem11Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem11Label.setObjectName("mem11Label")
        self.verticalLayout_5.addWidget(self.mem11Label)
        self.mem12Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem12Label.setFont(font)
        self.mem12Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem12Label.setObjectName("mem12Label")
        self.verticalLayout_5.addWidget(self.mem12Label)
        self.mem13Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem13Label.setFont(font)
        self.mem13Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem13Label.setObjectName("mem13Label")
        self.verticalLayout_5.addWidget(self.mem13Label)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mem21Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem21Label.setFont(font)
        self.mem21Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem21Label.setObjectName("mem21Label")
        self.verticalLayout_6.addWidget(self.mem21Label)
        self.mem22Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem22Label.setFont(font)
        self.mem22Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem22Label.setObjectName("mem22Label")
        self.verticalLayout_6.addWidget(self.mem22Label)
        self.mem23Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem23Label.setFont(font)
        self.mem23Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem23Label.setObjectName("mem23Label")
        self.verticalLayout_6.addWidget(self.mem23Label)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mem31Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem31Label.setFont(font)
        self.mem31Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem31Label.setObjectName("mem31Label")
        self.verticalLayout_7.addWidget(self.mem31Label)
        self.mem32Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem32Label.setFont(font)
        self.mem32Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem32Label.setObjectName("mem32Label")
        self.verticalLayout_7.addWidget(self.mem32Label)
        self.mem33Label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem33Label.setFont(font)
        self.mem33Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem33Label.setObjectName("mem33Label")
        self.verticalLayout_7.addWidget(self.mem33Label)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.pulseDurationLabel = QtWidgets.QLabel(Dialog)
        self.pulseDurationLabel.setGeometry(QtCore.QRect(700, 600, 136, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pulseDurationLabel.setFont(font)
        self.pulseDurationLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.pulseDurationLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pulseDurationLabel.setObjectName("pulseDurationLabel")
        self.powerRedLabel = QtWidgets.QLabel(Dialog)
        self.powerRedLabel.setGeometry(QtCore.QRect(105, 510, 166, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.powerRedLabel.setFont(font)
        self.powerRedLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.powerRedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.powerRedLabel.setObjectName("powerRedLabel")
        self.date_timeLabel = QtWidgets.QLabel(Dialog)
        self.date_timeLabel.setGeometry(QtCore.QRect(910, 40, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.date_timeLabel.setFont(font)
        self.date_timeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.date_timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_timeLabel.setObjectName("date_timeLabel")
        self.diagButton = QtWidgets.QPushButton(Dialog)
        self.diagButton.setGeometry(QtCore.QRect(90, 30, 141, 41))
        self.diagButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px")
        self.diagButton.setText("")
        self.diagButton.setObjectName("diagButton")
        self.powerIRedLabel = QtWidgets.QLabel(Dialog)
        self.powerIRedLabel.setGeometry(QtCore.QRect(105, 660, 166, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.powerIRedLabel.setFont(font)
        self.powerIRedLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.powerIRedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.powerIRedLabel.setObjectName("powerIRedLabel")
        self.layoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(575, 135, 661, 102))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.step1Button = QtWidgets.QPushButton(self.layoutWidget_6)
        self.step1Button.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.step1Button.setFont(font)
        self.step1Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step1Button.setStyleSheet("background-color: rgb(245, 233, 233);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.step1Button.setObjectName("step1Button")
        self.horizontalLayout_5.addWidget(self.step1Button)
        self.step2Button = QtWidgets.QPushButton(self.layoutWidget_6)
        self.step2Button.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.step2Button.setFont(font)
        self.step2Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step2Button.setStyleSheet("background-color: rgb(243, 220, 220);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.step2Button.setObjectName("step2Button")
        self.horizontalLayout_5.addWidget(self.step2Button)
        self.step3Button = QtWidgets.QPushButton(self.layoutWidget_6)
        self.step3Button.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.step3Button.setFont(font)
        self.step3Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step3Button.setStyleSheet("background-color: rgb(241, 207, 206);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.step3Button.setObjectName("step3Button")
        self.horizontalLayout_5.addWidget(self.step3Button)
        self.step4Button = QtWidgets.QPushButton(self.layoutWidget_6)
        self.step4Button.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.step4Button.setFont(font)
        self.step4Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step4Button.setStyleSheet("background-color: rgb(238, 194, 195);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.step4Button.setObjectName("step4Button")
        self.horizontalLayout_5.addWidget(self.step4Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.stepPauseButton = QtWidgets.QPushButton(self.layoutWidget_6)
        self.stepPauseButton.setMinimumSize(QtCore.QSize(180, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.stepPauseButton.setFont(font)
        self.stepPauseButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stepPauseButton.setStyleSheet("background-color: rgb(214, 216, 240);\n"
"color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.stepPauseButton.setObjectName("stepPauseButton")
        self.horizontalLayout_5.addWidget(self.stepPauseButton)
        self.layoutWidget_7 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_7.setGeometry(QtCore.QRect(280, 640, 231, 102))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(22)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.powerDwnIRedButton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.powerDwnIRedButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerDwnIRedButton.setStyleSheet("background-image: url(:/buttons/resources/Abajo.png);\n"
"background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerDwnIRedButton.setText("")
        self.powerDwnIRedButton.setObjectName("powerDwnIRedButton")
        self.horizontalLayout_6.addWidget(self.powerDwnIRedButton)
        self.powerUpIRedButton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.powerUpIRedButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerUpIRedButton.setStyleSheet("background-image: url(:/buttons/resources/Arriba.png);\n"
"background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerUpIRedButton.setText("")
        self.powerUpIRedButton.setObjectName("powerUpIRedButton")
        self.horizontalLayout_6.addWidget(self.powerUpIRedButton)
        self.layoutWidget_8 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_8.setGeometry(QtCore.QRect(280, 490, 231, 102))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(22)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.powerDwnRedButton = QtWidgets.QPushButton(self.layoutWidget_8)
        self.powerDwnRedButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerDwnRedButton.setStyleSheet("background-image: url(:/buttons/resources/Abajo.png);\n"
"background-color: rgb(242, 248, 250);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerDwnRedButton.setText("")
        self.powerDwnRedButton.setObjectName("powerDwnRedButton")
        self.horizontalLayout_7.addWidget(self.powerDwnRedButton)
        self.powerUpRedButton = QtWidgets.QPushButton(self.layoutWidget_8)
        self.powerUpRedButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerUpRedButton.setStyleSheet("background-image: url(:/buttons/resources/Arriba.png);\n"
"background-color: rgb(138, 186, 210);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerUpRedButton.setText("")
        self.powerUpRedButton.setObjectName("powerUpRedButton")
        self.horizontalLayout_7.addWidget(self.powerUpRedButton)
        self.layoutWidget_9 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_9.setGeometry(QtCore.QRect(655, 660, 236, 102))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(22)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pulseDwnButton = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pulseDwnButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pulseDwnButton.setStyleSheet("background-image: url(:/buttons/resources/Abajo.png);\n"
"background-color: rgb(242, 248, 250);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.pulseDwnButton.setText("")
        self.pulseDwnButton.setObjectName("pulseDwnButton")
        self.horizontalLayout_8.addWidget(self.pulseDwnButton)
        self.pulseUpButton = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pulseUpButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pulseUpButton.setStyleSheet("background-image: url(:/buttons/resources/Arriba.png);\n"
"background-color: rgb(138, 186, 210);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.pulseUpButton.setText("")
        self.pulseUpButton.setObjectName("pulseUpButton")
        self.horizontalLayout_8.addWidget(self.pulseUpButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pannelAButton.setText(_translate("Dialog", "A"))
        self.pannelBButton.setText(_translate("Dialog", "B"))
        self.pannelCButton.setText(_translate("Dialog", "C"))
        self.pannelDButton.setText(_translate("Dialog", "D"))
        self.pannelEButton.setText(_translate("Dialog", "E"))
        self.mem1Button.setText(_translate("Dialog", "I"))
        self.mem2Button.setText(_translate("Dialog", "II"))
        self.mem3Button.setText(_translate("Dialog", "III"))
        self.mem11Label.setText(_translate("Dialog", "110min"))
        self.mem12Label.setText(_translate("Dialog", "11.75Hz - 100%"))
        self.mem13Label.setText(_translate("Dialog", "Sinusoidal"))
        self.mem21Label.setText(_translate("Dialog", "110min"))
        self.mem22Label.setText(_translate("Dialog", "11.75Hz - 100%"))
        self.mem23Label.setText(_translate("Dialog", "Sinusoidal"))
        self.mem31Label.setText(_translate("Dialog", "110min"))
        self.mem32Label.setText(_translate("Dialog", "11.75Hz - 100%"))
        self.mem33Label.setText(_translate("Dialog", "Sinusoidal"))
        self.pulseDurationLabel.setText(_translate("Dialog", "2000"))
        self.powerRedLabel.setText(_translate("Dialog", "100%"))
        self.date_timeLabel.setText(_translate("Dialog", "19/03/2020 - 17:45"))
        self.powerIRedLabel.setText(_translate("Dialog", "100%"))
        self.step1Button.setText(_translate("Dialog", "1"))
        self.step2Button.setText(_translate("Dialog", "2"))
        self.step3Button.setText(_translate("Dialog", "3"))
        self.step4Button.setText(_translate("Dialog", "4"))
        self.stepPauseButton.setText(_translate("Dialog", "Pause"))

import light1_res_rc
