# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magnet_ver_4_1.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 800)
        Dialog.setStyleSheet("QDialog {\n"
"    background-image: url(:/background/resources/bkg_main_no_buttons.png);\n"
"}")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(785, 630, 396, 146))
        self.startButton.setMinimumSize(QtCore.QSize(100, 100))
        self.startButton.setStyleSheet("background-image: url(:/buttons/resources/Play.png);\n"
"background-color: rgb(0, 168, 89);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.startButton.setText("")
        self.startButton.setObjectName("startButton")
        self.totalMinutesLabel = QtWidgets.QLabel(Dialog)
        self.totalMinutesLabel.setGeometry(QtCore.QRect(340, 90, 166, 81))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(56)
        font.setBold(True)
        font.setWeight(75)
        self.totalMinutesLabel.setFont(font)
        self.totalMinutesLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.totalMinutesLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.totalMinutesLabel.setObjectName("totalMinutesLabel")
        self.date_timeLabel = QtWidgets.QLabel(Dialog)
        self.date_timeLabel.setGeometry(QtCore.QRect(910, 40, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.date_timeLabel.setFont(font)
        self.date_timeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.date_timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_timeLabel.setObjectName("date_timeLabel")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(25, 655, 656, 121))
        self.textEdit.setStyleSheet("border:3px outset;\n"
"background-color: rgb(254, 254, 254);\n"
"border-radius: 16px;\n"
"color: rgb(0, 0, 127);\n"
"border-color: rgb(55, 52, 53);")
        self.textEdit.setObjectName("textEdit")
        self.diagButton = QtWidgets.QPushButton(Dialog)
        self.diagButton.setGeometry(QtCore.QRect(45, 30, 186, 41))
        self.diagButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px")
        self.diagButton.setText("")
        self.diagButton.setObjectName("diagButton")
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(25, 515, 656, 102))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ch1Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1Button.sizePolicy().hasHeightForWidth())
        self.ch1Button.setSizePolicy(sizePolicy)
        self.ch1Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch1Button.setFont(font)
        self.ch1Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1Button.setStyleSheet("background-color: rgb(191, 211, 199);\n"
"border-radius: 16px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch1Button.setObjectName("ch1Button")
        self.horizontalLayout_4.addWidget(self.ch1Button)
        self.ch2Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2Button.sizePolicy().hasHeightForWidth())
        self.ch2Button.setSizePolicy(sizePolicy)
        self.ch2Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch2Button.setFont(font)
        self.ch2Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch2Button.setStyleSheet("background-color: rgb(191, 211, 199);\n"
"border-radius: 16px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch2Button.setObjectName("ch2Button")
        self.horizontalLayout_4.addWidget(self.ch2Button)
        self.ch3Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch3Button.sizePolicy().hasHeightForWidth())
        self.ch3Button.setSizePolicy(sizePolicy)
        self.ch3Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch3Button.setFont(font)
        self.ch3Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch3Button.setStyleSheet("background-color: rgb(191, 211, 199);\n"
"border-radius: 16px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch3Button.setObjectName("ch3Button")
        self.horizontalLayout_4.addWidget(self.ch3Button)
        self.ch4Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch4Button.sizePolicy().hasHeightForWidth())
        self.ch4Button.setSizePolicy(sizePolicy)
        self.ch4Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch4Button.setFont(font)
        self.ch4Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch4Button.setStyleSheet("background-color: rgb(191, 211, 199);\n"
"border-radius: 16px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch4Button.setObjectName("ch4Button")
        self.horizontalLayout_4.addWidget(self.ch4Button)
        self.wifiButton = QtWidgets.QPushButton(Dialog)
        self.wifiButton.setGeometry(QtCore.QRect(835, 5, 100, 71))
        self.wifiButton.setMinimumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.wifiButton.setFont(font)
        self.wifiButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.wifiButton.setStyleSheet("color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.wifiButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/resources/wifi-symbol_disa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wifiButton.setIcon(icon)
        self.wifiButton.setIconSize(QtCore.QSize(75, 75))
        self.wifiButton.setObjectName("wifiButton")
        self.memManagerButton = QtWidgets.QPushButton(Dialog)
        self.memManagerButton.setGeometry(QtCore.QRect(965, 540, 291, 56))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memManagerButton.sizePolicy().hasHeightForWidth())
        self.memManagerButton.setSizePolicy(sizePolicy)
        self.memManagerButton.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.memManagerButton.setFont(font)
        self.memManagerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.memManagerButton.setStyleSheet("background-color: rgb(134, 152, 188);\n"
"border-radius: 16px;\n"
"border:3px solid rgb(55, 52, 53);\n"
"color: rgb(55, 52, 53);")
        self.memManagerButton.setObjectName("memManagerButton")
        self.stage1MinutesLabel = QtWidgets.QLabel(Dialog)
        self.stage1MinutesLabel.setGeometry(QtCore.QRect(40, 260, 166, 66))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.stage1MinutesLabel.setFont(font)
        self.stage1MinutesLabel.setStyleSheet("color: rgb(62, 64, 149);")
        self.stage1MinutesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stage1MinutesLabel.setObjectName("stage1MinutesLabel")
        self.stage1Button = QtWidgets.QPushButton(Dialog)
        self.stage1Button.setGeometry(QtCore.QRect(25, 205, 200, 270))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage1Button.sizePolicy().hasHeightForWidth())
        self.stage1Button.setSizePolicy(sizePolicy)
        self.stage1Button.setMinimumSize(QtCore.QSize(90, 90))
        self.stage1Button.setMaximumSize(QtCore.QSize(200, 270))
        self.stage1Button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.stage1Button.setText("")
        self.stage1Button.setObjectName("stage1Button")
        self.stage3PowerLabel = QtWidgets.QLabel(Dialog)
        self.stage3PowerLabel.setGeometry(QtCore.QRect(480, 305, 206, 81))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.stage3PowerLabel.setFont(font)
        self.stage3PowerLabel.setStyleSheet("color: rgb(237, 50, 55);")
        self.stage3PowerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stage3PowerLabel.setObjectName("stage3PowerLabel")
        self.stage2PowerLabel = QtWidgets.QLabel(Dialog)
        self.stage2PowerLabel.setGeometry(QtCore.QRect(250, 305, 206, 81))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.stage2PowerLabel.setFont(font)
        self.stage2PowerLabel.setStyleSheet("color: rgb(237, 50, 55);")
        self.stage2PowerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stage2PowerLabel.setObjectName("stage2PowerLabel")
        self.stage2SignalButton = QtWidgets.QPushButton(Dialog)
        self.stage2SignalButton.setGeometry(QtCore.QRect(270, 385, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage2SignalButton.sizePolicy().hasHeightForWidth())
        self.stage2SignalButton.setSizePolicy(sizePolicy)
        self.stage2SignalButton.setMinimumSize(QtCore.QSize(75, 75))
        self.stage2SignalButton.setStyleSheet("background-image: url(:/buttons/resources/square_75_75.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(237, 211, 152);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage2SignalButton.setText("")
        self.stage2SignalButton.setObjectName("stage2SignalButton")
        self.stage2MinutesLabel = QtWidgets.QLabel(Dialog)
        self.stage2MinutesLabel.setGeometry(QtCore.QRect(265, 260, 166, 66))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.stage2MinutesLabel.setFont(font)
        self.stage2MinutesLabel.setStyleSheet("color: rgb(62, 64, 149);")
        self.stage2MinutesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stage2MinutesLabel.setObjectName("stage2MinutesLabel")
        self.stage1Label = QtWidgets.QLabel(Dialog)
        self.stage1Label.setGeometry(QtCore.QRect(25, 205, 201, 271))
        self.stage1Label.setStyleSheet("background-image: url(:/stage_buttons/resources/stage1_enable.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage1Label.setText("")
        self.stage1Label.setObjectName("stage1Label")
        self.stage2FreqButton = QtWidgets.QPushButton(Dialog)
        self.stage2FreqButton.setGeometry(QtCore.QRect(360, 385, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage2FreqButton.sizePolicy().hasHeightForWidth())
        self.stage2FreqButton.setSizePolicy(sizePolicy)
        self.stage2FreqButton.setMinimumSize(QtCore.QSize(75, 75))
        self.stage2FreqButton.setStyleSheet("background-image: url(:/frequencies/resources/freq9_75_75.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(220, 188, 203);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage2FreqButton.setText("")
        self.stage2FreqButton.setObjectName("stage2FreqButton")
        self.stage3SignalButton = QtWidgets.QPushButton(Dialog)
        self.stage3SignalButton.setGeometry(QtCore.QRect(500, 385, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage3SignalButton.sizePolicy().hasHeightForWidth())
        self.stage3SignalButton.setSizePolicy(sizePolicy)
        self.stage3SignalButton.setMinimumSize(QtCore.QSize(75, 75))
        self.stage3SignalButton.setStyleSheet("background-image: url(:/buttons/resources/sinus_75_75.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(237, 211, 152);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage3SignalButton.setText("")
        self.stage3SignalButton.setObjectName("stage3SignalButton")
        self.stage1PowerLabel = QtWidgets.QLabel(Dialog)
        self.stage1PowerLabel.setGeometry(QtCore.QRect(25, 305, 206, 81))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.stage1PowerLabel.setFont(font)
        self.stage1PowerLabel.setStyleSheet("color: rgb(237, 50, 55);")
        self.stage1PowerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stage1PowerLabel.setObjectName("stage1PowerLabel")
        self.stage1SignalButton = QtWidgets.QPushButton(Dialog)
        self.stage1SignalButton.setGeometry(QtCore.QRect(45, 385, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage1SignalButton.sizePolicy().hasHeightForWidth())
        self.stage1SignalButton.setSizePolicy(sizePolicy)
        self.stage1SignalButton.setMinimumSize(QtCore.QSize(75, 75))
        self.stage1SignalButton.setStyleSheet("background-image: url(:/buttons/resources/triangular_75_75.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(237, 211, 152);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage1SignalButton.setText("")
        self.stage1SignalButton.setObjectName("stage1SignalButton")
        self.stage2Label = QtWidgets.QLabel(Dialog)
        self.stage2Label.setGeometry(QtCore.QRect(250, 205, 201, 271))
        self.stage2Label.setStyleSheet("background-image: url(:/stage_buttons/resources/stage2_enable.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage2Label.setText("")
        self.stage2Label.setObjectName("stage2Label")
        self.stage1FreqButton = QtWidgets.QPushButton(Dialog)
        self.stage1FreqButton.setGeometry(QtCore.QRect(135, 385, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage1FreqButton.sizePolicy().hasHeightForWidth())
        self.stage1FreqButton.setSizePolicy(sizePolicy)
        self.stage1FreqButton.setMinimumSize(QtCore.QSize(75, 75))
        self.stage1FreqButton.setStyleSheet("background-image: url(:/frequencies/resources/freq1_75_75.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(220, 188, 203);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage1FreqButton.setText("")
        self.stage1FreqButton.setObjectName("stage1FreqButton")
        self.stage3Button = QtWidgets.QPushButton(Dialog)
        self.stage3Button.setGeometry(QtCore.QRect(480, 205, 200, 270))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage3Button.sizePolicy().hasHeightForWidth())
        self.stage3Button.setSizePolicy(sizePolicy)
        self.stage3Button.setMinimumSize(QtCore.QSize(90, 90))
        self.stage3Button.setMaximumSize(QtCore.QSize(200, 270))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.stage3Button.setFont(font)
        self.stage3Button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.stage3Button.setText("")
        self.stage3Button.setObjectName("stage3Button")
        self.stage3FreqButton = QtWidgets.QPushButton(Dialog)
        self.stage3FreqButton.setGeometry(QtCore.QRect(590, 385, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage3FreqButton.sizePolicy().hasHeightForWidth())
        self.stage3FreqButton.setSizePolicy(sizePolicy)
        self.stage3FreqButton.setMinimumSize(QtCore.QSize(75, 75))
        self.stage3FreqButton.setStyleSheet("background-image: url(:/frequencies/resources/freq10_75_75.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(220, 188, 203);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage3FreqButton.setText("")
        self.stage3FreqButton.setObjectName("stage3FreqButton")
        self.stage2Button = QtWidgets.QPushButton(Dialog)
        self.stage2Button.setGeometry(QtCore.QRect(250, 205, 200, 270))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage2Button.sizePolicy().hasHeightForWidth())
        self.stage2Button.setSizePolicy(sizePolicy)
        self.stage2Button.setMinimumSize(QtCore.QSize(90, 90))
        self.stage2Button.setMaximumSize(QtCore.QSize(200, 270))
        self.stage2Button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.stage2Button.setText("")
        self.stage2Button.setObjectName("stage2Button")
        self.stage3Label = QtWidgets.QLabel(Dialog)
        self.stage3Label.setGeometry(QtCore.QRect(480, 205, 201, 271))
        self.stage3Label.setStyleSheet("background-image: url(:/stage_buttons/resources/stage3_enable.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center center;\n"
"background-color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);")
        self.stage3Label.setText("")
        self.stage3Label.setObjectName("stage3Label")
        self.stage3MinutesLabel = QtWidgets.QLabel(Dialog)
        self.stage3MinutesLabel.setGeometry(QtCore.QRect(495, 260, 166, 66))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.stage3MinutesLabel.setFont(font)
        self.stage3MinutesLabel.setStyleSheet("color: rgb(62, 64, 149);")
        self.stage3MinutesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stage3MinutesLabel.setObjectName("stage3MinutesLabel")
        self.membButton = QtWidgets.QPushButton(Dialog)
        self.membButton.setGeometry(QtCore.QRect(735, 225, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membButton.sizePolicy().hasHeightForWidth())
        self.membButton.setSizePolicy(sizePolicy)
        self.membButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.membButton.setFont(font)
        self.membButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.membButton.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(230, 231, 232);\n"
"color: rgb(230,231,232);")
        self.membButton.setObjectName("membButton")
        self.memaButton = QtWidgets.QPushButton(Dialog)
        self.memaButton.setGeometry(QtCore.QRect(735, 125, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memaButton.sizePolicy().hasHeightForWidth())
        self.memaButton.setSizePolicy(sizePolicy)
        self.memaButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.memaButton.setFont(font)
        self.memaButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.memaButton.setStyleSheet("background-color: rgb(221, 234, 224);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(55, 52, 53);\n"
"color: rgb(55, 52, 53);")
        self.memaButton.setObjectName("memaButton")
        self.memcButton = QtWidgets.QPushButton(Dialog)
        self.memcButton.setGeometry(QtCore.QRect(735, 325, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memcButton.sizePolicy().hasHeightForWidth())
        self.memcButton.setSizePolicy(sizePolicy)
        self.memcButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.memcButton.setFont(font)
        self.memcButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.memcButton.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(230, 231, 232);\n"
"color: rgb(230,231,232);")
        self.memcButton.setObjectName("memcButton")
        self.memdButton = QtWidgets.QPushButton(Dialog)
        self.memdButton.setGeometry(QtCore.QRect(735, 425, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memdButton.sizePolicy().hasHeightForWidth())
        self.memdButton.setSizePolicy(sizePolicy)
        self.memdButton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.memdButton.setFont(font)
        self.memdButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.memdButton.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 20px;\n"
"border:3px solid rgb(230, 231, 232);\n"
"color: rgb(230,231,232);")
        self.memdButton.setObjectName("memdButton")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(840, 120, 401, 396))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.memaDescLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memaDescLabel.sizePolicy().hasHeightForWidth())
        self.memaDescLabel.setSizePolicy(sizePolicy)
        self.memaDescLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.memaDescLabel.setFont(font)
        self.memaDescLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memaDescLabel.setObjectName("memaDescLabel")
        self.verticalLayout_10.addWidget(self.memaDescLabel)
        self.memaOneLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memaOneLabel.sizePolicy().hasHeightForWidth())
        self.memaOneLabel.setSizePolicy(sizePolicy)
        self.memaOneLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memaOneLabel.setFont(font)
        self.memaOneLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memaOneLabel.setObjectName("memaOneLabel")
        self.verticalLayout_10.addWidget(self.memaOneLabel)
        self.memaTwoLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memaTwoLabel.sizePolicy().hasHeightForWidth())
        self.memaTwoLabel.setSizePolicy(sizePolicy)
        self.memaTwoLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memaTwoLabel.setFont(font)
        self.memaTwoLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memaTwoLabel.setObjectName("memaTwoLabel")
        self.verticalLayout_10.addWidget(self.memaTwoLabel)
        self.memaThreeLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memaThreeLabel.sizePolicy().hasHeightForWidth())
        self.memaThreeLabel.setSizePolicy(sizePolicy)
        self.memaThreeLabel.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memaThreeLabel.setFont(font)
        self.memaThreeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memaThreeLabel.setObjectName("memaThreeLabel")
        self.verticalLayout_10.addWidget(self.memaThreeLabel)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.membDescLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membDescLabel.sizePolicy().hasHeightForWidth())
        self.membDescLabel.setSizePolicy(sizePolicy)
        self.membDescLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.membDescLabel.setFont(font)
        self.membDescLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.membDescLabel.setObjectName("membDescLabel")
        self.verticalLayout_11.addWidget(self.membDescLabel)
        self.membOneLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membOneLabel.sizePolicy().hasHeightForWidth())
        self.membOneLabel.setSizePolicy(sizePolicy)
        self.membOneLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.membOneLabel.setFont(font)
        self.membOneLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.membOneLabel.setObjectName("membOneLabel")
        self.verticalLayout_11.addWidget(self.membOneLabel)
        self.membTwoLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membTwoLabel.sizePolicy().hasHeightForWidth())
        self.membTwoLabel.setSizePolicy(sizePolicy)
        self.membTwoLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.membTwoLabel.setFont(font)
        self.membTwoLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.membTwoLabel.setObjectName("membTwoLabel")
        self.verticalLayout_11.addWidget(self.membTwoLabel)
        self.membThreeLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membThreeLabel.sizePolicy().hasHeightForWidth())
        self.membThreeLabel.setSizePolicy(sizePolicy)
        self.membThreeLabel.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.membThreeLabel.setFont(font)
        self.membThreeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.membThreeLabel.setObjectName("membThreeLabel")
        self.verticalLayout_11.addWidget(self.membThreeLabel)
        self.verticalLayout_8.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.memcDescLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memcDescLabel.sizePolicy().hasHeightForWidth())
        self.memcDescLabel.setSizePolicy(sizePolicy)
        self.memcDescLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.memcDescLabel.setFont(font)
        self.memcDescLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memcDescLabel.setObjectName("memcDescLabel")
        self.verticalLayout_13.addWidget(self.memcDescLabel)
        self.memcOneLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memcOneLabel.sizePolicy().hasHeightForWidth())
        self.memcOneLabel.setSizePolicy(sizePolicy)
        self.memcOneLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memcOneLabel.setFont(font)
        self.memcOneLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memcOneLabel.setObjectName("memcOneLabel")
        self.verticalLayout_13.addWidget(self.memcOneLabel)
        self.memcTwoLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memcTwoLabel.sizePolicy().hasHeightForWidth())
        self.memcTwoLabel.setSizePolicy(sizePolicy)
        self.memcTwoLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memcTwoLabel.setFont(font)
        self.memcTwoLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memcTwoLabel.setObjectName("memcTwoLabel")
        self.verticalLayout_13.addWidget(self.memcTwoLabel)
        self.memcThreeLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memcThreeLabel.sizePolicy().hasHeightForWidth())
        self.memcThreeLabel.setSizePolicy(sizePolicy)
        self.memcThreeLabel.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memcThreeLabel.setFont(font)
        self.memcThreeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memcThreeLabel.setObjectName("memcThreeLabel")
        self.verticalLayout_13.addWidget(self.memcThreeLabel)
        self.verticalLayout_8.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.memdDescLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memdDescLabel.sizePolicy().hasHeightForWidth())
        self.memdDescLabel.setSizePolicy(sizePolicy)
        self.memdDescLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.memdDescLabel.setFont(font)
        self.memdDescLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memdDescLabel.setObjectName("memdDescLabel")
        self.verticalLayout_12.addWidget(self.memdDescLabel)
        self.memdOneLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memdOneLabel.sizePolicy().hasHeightForWidth())
        self.memdOneLabel.setSizePolicy(sizePolicy)
        self.memdOneLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memdOneLabel.setFont(font)
        self.memdOneLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memdOneLabel.setObjectName("memdOneLabel")
        self.verticalLayout_12.addWidget(self.memdOneLabel)
        self.memdTwoLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memdTwoLabel.sizePolicy().hasHeightForWidth())
        self.memdTwoLabel.setSizePolicy(sizePolicy)
        self.memdTwoLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memdTwoLabel.setFont(font)
        self.memdTwoLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memdTwoLabel.setObjectName("memdTwoLabel")
        self.verticalLayout_12.addWidget(self.memdTwoLabel)
        self.memdThreeLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memdThreeLabel.sizePolicy().hasHeightForWidth())
        self.memdThreeLabel.setSizePolicy(sizePolicy)
        self.memdThreeLabel.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.memdThreeLabel.setFont(font)
        self.memdThreeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.memdThreeLabel.setObjectName("memdThreeLabel")
        self.verticalLayout_12.addWidget(self.memdThreeLabel)
        self.verticalLayout_8.addLayout(self.verticalLayout_12)
        self.securityButton = QtWidgets.QPushButton(Dialog)
        self.securityButton.setGeometry(QtCore.QRect(725, 5, 100, 71))
        self.securityButton.setMinimumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.securityButton.setFont(font)
        self.securityButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.securityButton.setStyleSheet("color: rgb(55, 52, 53);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.securityButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/resources/key_unknow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.securityButton.setIcon(icon1)
        self.securityButton.setIconSize(QtCore.QSize(75, 75))
        self.securityButton.setObjectName("securityButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.totalMinutesLabel.setText(_translate("Dialog", "105"))
        self.date_timeLabel.setText(_translate("Dialog", "19/03/2020 - 17:45"))
        self.ch1Button.setText(_translate("Dialog", "CH1"))
        self.ch2Button.setText(_translate("Dialog", "CH2"))
        self.ch3Button.setText(_translate("Dialog", "CH3"))
        self.ch4Button.setText(_translate("Dialog", "CH4"))
        self.memManagerButton.setText(_translate("Dialog", "Memory Manager"))
        self.stage1MinutesLabel.setText(_translate("Dialog", "45\'"))
        self.stage3PowerLabel.setText(_translate("Dialog", "100%"))
        self.stage2PowerLabel.setText(_translate("Dialog", "100%"))
        self.stage2MinutesLabel.setText(_translate("Dialog", "60\'"))
        self.stage1PowerLabel.setText(_translate("Dialog", "85%"))
        self.stage3MinutesLabel.setText(_translate("Dialog", "60\'"))
        self.membButton.setText(_translate("Dialog", "B"))
        self.memaButton.setText(_translate("Dialog", "A"))
        self.memcButton.setText(_translate("Dialog", "C"))
        self.memdButton.setText(_translate("Dialog", "D"))
        self.memaDescLabel.setText(_translate("Dialog", "Arm and Leg Inflammatory"))
        self.memaOneLabel.setText(_translate("Dialog", "1 - 45\' T 85% 7.83Hz"))
        self.memaTwoLabel.setText(_translate("Dialog", "2 - 60\' S 100% 62.64Hz"))
        self.memaThreeLabel.setText(_translate("Dialog", "3 -"))
        self.membDescLabel.setText(_translate("Dialog", "Arm and Leg Inflammatory"))
        self.membOneLabel.setText(_translate("Dialog", "1 - 45\' T 85% 7.83Hz"))
        self.membTwoLabel.setText(_translate("Dialog", "2 - 60\' S 100% 62.64Hz"))
        self.membThreeLabel.setText(_translate("Dialog", "3 -"))
        self.memcDescLabel.setText(_translate("Dialog", "Arm and Leg Inflammatory"))
        self.memcOneLabel.setText(_translate("Dialog", "1 - 45\' T 85% 7.83Hz"))
        self.memcTwoLabel.setText(_translate("Dialog", "2 - 60\' S 100% 62.64Hz"))
        self.memcThreeLabel.setText(_translate("Dialog", "3 -"))
        self.memdDescLabel.setText(_translate("Dialog", "Arm and Leg Inflammatory"))
        self.memdOneLabel.setText(_translate("Dialog", "1 - 45\' T 85% 7.83Hz"))
        self.memdTwoLabel.setText(_translate("Dialog", "2 - 60\' S 100% 62.64Hz"))
        self.memdThreeLabel.setText(_translate("Dialog", "3 -"))

import magnet4_res_rc
