# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnostics.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DiagnosticsDialog(object):
    def setupUi(self, DiagnosticsDialog):
        DiagnosticsDialog.setObjectName("DiagnosticsDialog")
        DiagnosticsDialog.resize(1280, 800)
        DiagnosticsDialog.setStyleSheet("QDialog {\n"
"background-image: url(:/background/resources/bkg_solo_logo.png);\n"
"}")
        self.label_3 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 154, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAcceptDrops(True)
        self.label_3.setObjectName("label_3")
        self.hardwareLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.hardwareLabel.setGeometry(QtCore.QRect(160, 120, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hardwareLabel.setFont(font)
        self.hardwareLabel.setObjectName("hardwareLabel")
        self.label_2 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 370, 34))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 150, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_7.setGeometry(QtCore.QRect(430, 150, 248, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.highVLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.highVLabel.setGeometry(QtCore.QRect(690, 120, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.highVLabel.setFont(font)
        self.highVLabel.setObjectName("highVLabel")
        self.label_4 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_4.setGeometry(QtCore.QRect(430, 120, 256, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lowVLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.lowVLabel.setGeometry(QtCore.QRect(690, 150, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lowVLabel.setFont(font)
        self.lowVLabel.setObjectName("lowVLabel")
        self.firmwareLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.firmwareLabel.setGeometry(QtCore.QRect(160, 150, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.firmwareLabel.setFont(font)
        self.firmwareLabel.setObjectName("firmwareLabel")
        self.label_12 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_12.setGeometry(QtCore.QRect(10, 280, 50, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.osLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.osLabel.setGeometry(QtCore.QRect(100, 280, 651, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.osLabel.setFont(font)
        self.osLabel.setText("")
        self.osLabel.setObjectName("osLabel")
        self.label_6 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 370, 34))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_13.setGeometry(QtCore.QRect(10, 310, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.kernelLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.kernelLabel.setGeometry(QtCore.QRect(100, 310, 651, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kernelLabel.setFont(font)
        self.kernelLabel.setText("")
        self.kernelLabel.setObjectName("kernelLabel")
        self.label_11 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_11.setGeometry(QtCore.QRect(10, 405, 370, 34))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_8.setGeometry(QtCore.QRect(10, 450, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.softLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.softLabel.setGeometry(QtCore.QRect(160, 445, 611, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.softLabel.setFont(font)
        self.softLabel.setText("")
        self.softLabel.setObjectName("softLabel")
        self.doneButton = QtWidgets.QPushButton(DiagnosticsDialog)
        self.doneButton.setGeometry(QtCore.QRect(980, 670, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.doneButton.setFont(font)
        self.doneButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doneButton.setObjectName("doneButton")
        self.lanButton = QtWidgets.QPushButton(DiagnosticsDialog)
        self.lanButton.setGeometry(QtCore.QRect(500, 550, 200, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lanButton.sizePolicy().hasHeightForWidth())
        self.lanButton.setSizePolicy(sizePolicy)
        self.lanButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lanButton.setFont(font)
        self.lanButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lanButton.setObjectName("lanButton")
        self.max_powerButton = QtWidgets.QPushButton(DiagnosticsDialog)
        self.max_powerButton.setGeometry(QtCore.QRect(260, 550, 200, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_powerButton.sizePolicy().hasHeightForWidth())
        self.max_powerButton.setSizePolicy(sizePolicy)
        self.max_powerButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.max_powerButton.setFont(font)
        self.max_powerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.max_powerButton.setObjectName("max_powerButton")
        self.rtcButton = QtWidgets.QPushButton(DiagnosticsDialog)
        self.rtcButton.setGeometry(QtCore.QRect(20, 550, 200, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rtcButton.sizePolicy().hasHeightForWidth())
        self.rtcButton.setSizePolicy(sizePolicy)
        self.rtcButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.rtcButton.setFont(font)
        self.rtcButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rtcButton.setObjectName("rtcButton")
        self.localizationButton = QtWidgets.QPushButton(DiagnosticsDialog)
        self.localizationButton.setGeometry(QtCore.QRect(20, 670, 200, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localizationButton.sizePolicy().hasHeightForWidth())
        self.localizationButton.setSizePolicy(sizePolicy)
        self.localizationButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.localizationButton.setFont(font)
        self.localizationButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.localizationButton.setObjectName("localizationButton")
        self.display_modeButton = QtWidgets.QPushButton(DiagnosticsDialog)
        self.display_modeButton.setGeometry(QtCore.QRect(260, 670, 200, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_modeButton.sizePolicy().hasHeightForWidth())
        self.display_modeButton.setSizePolicy(sizePolicy)
        self.display_modeButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.display_modeButton.setFont(font)
        self.display_modeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.display_modeButton.setObjectName("display_modeButton")
        self.date_timeLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.date_timeLabel.setGeometry(QtCore.QRect(910, 40, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.date_timeLabel.setFont(font)
        self.date_timeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.date_timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_timeLabel.setObjectName("date_timeLabel")
        self.deviceLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.deviceLabel.setGeometry(QtCore.QRect(160, 180, 351, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.deviceLabel.setFont(font)
        self.deviceLabel.setObjectName("deviceLabel")
        self.label_9 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_9.setGeometry(QtCore.QRect(10, 180, 150, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.vncButton = QtWidgets.QPushButton(DiagnosticsDialog)
        self.vncButton.setGeometry(QtCore.QRect(500, 670, 200, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vncButton.sizePolicy().hasHeightForWidth())
        self.vncButton.setSizePolicy(sizePolicy)
        self.vncButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.vncButton.setFont(font)
        self.vncButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.vncButton.setObjectName("vncButton")
        self.macLabel = QtWidgets.QLabel(DiagnosticsDialog)
        self.macLabel.setGeometry(QtCore.QRect(100, 340, 651, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.macLabel.setFont(font)
        self.macLabel.setText("")
        self.macLabel.setObjectName("macLabel")
        self.label_14 = QtWidgets.QLabel(DiagnosticsDialog)
        self.label_14.setGeometry(QtCore.QRect(10, 340, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")

        self.retranslateUi(DiagnosticsDialog)
        QtCore.QMetaObject.connectSlotsByName(DiagnosticsDialog)

    def retranslateUi(self, DiagnosticsDialog):
        _translate = QtCore.QCoreApplication.translate
        DiagnosticsDialog.setWindowTitle(_translate("DiagnosticsDialog", "Dialog"))
        self.label_3.setText(_translate("DiagnosticsDialog", "HW Version: "))
        self.hardwareLabel.setText(_translate("DiagnosticsDialog", "1.1"))
        self.label_2.setText(_translate("DiagnosticsDialog", "Power Board Diagnostics:"))
        self.label_5.setText(_translate("DiagnosticsDialog", "FW Version: "))
        self.label_7.setText(_translate("DiagnosticsDialog", "Low Voltage Supply: "))
        self.highVLabel.setText(_translate("DiagnosticsDialog", "200V"))
        self.label_4.setText(_translate("DiagnosticsDialog", "High Voltage Supply: "))
        self.lowVLabel.setText(_translate("DiagnosticsDialog", "15V"))
        self.firmwareLabel.setText(_translate("DiagnosticsDialog", "1.1"))
        self.label_12.setText(_translate("DiagnosticsDialog", "OS: "))
        self.label_6.setText(_translate("DiagnosticsDialog", "Display Board Info:"))
        self.label_13.setText(_translate("DiagnosticsDialog", "Kernel: "))
        self.label_11.setText(_translate("DiagnosticsDialog", "Display Software Info:"))
        self.label_8.setText(_translate("DiagnosticsDialog", "SW Version: "))
        self.doneButton.setText(_translate("DiagnosticsDialog", "Done!"))
        self.lanButton.setText(_translate("DiagnosticsDialog", "LAN Config"))
        self.max_powerButton.setText(_translate("DiagnosticsDialog", "Max Power Config"))
        self.rtcButton.setText(_translate("DiagnosticsDialog", "RTC Config"))
        self.localizationButton.setText(_translate("DiagnosticsDialog", "Localization\n"
"USA"))
        self.display_modeButton.setText(_translate("DiagnosticsDialog", "Display Mode"))
        self.date_timeLabel.setText(_translate("DiagnosticsDialog", "19/03/2020 - 17:45"))
        self.deviceLabel.setText(_translate("DiagnosticsDialog", "1.1"))
        self.label_9.setText(_translate("DiagnosticsDialog", "Device Id:"))
        self.vncButton.setText(_translate("DiagnosticsDialog", "VNC Tunnel"))
        self.label_14.setText(_translate("DiagnosticsDialog", "MAC:"))

import diagnostics_res_rc
