# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'power_control.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PowerControlDialog(object):
    def setupUi(self, PowerControlDialog):
        PowerControlDialog.setObjectName("PowerControlDialog")
        PowerControlDialog.resize(800, 500)
        self.sinusoidalButton = QtWidgets.QPushButton(PowerControlDialog)
        self.sinusoidalButton.setGeometry(QtCore.QRect(20, 360, 100, 100))
        self.sinusoidalButton.setMinimumSize(QtCore.QSize(100, 100))
        self.sinusoidalButton.setStyleSheet("background-image: url(:/buttons/resources/Sinus.png);\n"
"background-color: rgb(240, 238, 126);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.sinusoidalButton.setText("")
        self.sinusoidalButton.setObjectName("sinusoidalButton")
        self.triangularButton = QtWidgets.QPushButton(PowerControlDialog)
        self.triangularButton.setGeometry(QtCore.QRect(20, 80, 100, 100))
        self.triangularButton.setMinimumSize(QtCore.QSize(100, 100))
        self.triangularButton.setStyleSheet("background-image: url(:/buttons/resources/Triangular.png);\n"
"background-color: rgb(248, 247, 190);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.triangularButton.setText("")
        self.triangularButton.setObjectName("triangularButton")
        self.squareButton = QtWidgets.QPushButton(PowerControlDialog)
        self.squareButton.setGeometry(QtCore.QRect(20, 220, 100, 100))
        self.squareButton.setMinimumSize(QtCore.QSize(100, 100))
        self.squareButton.setStyleSheet("background-image: url(:/buttons/resources/Cuadrada.png);\n"
"background-color: rgb(244, 243, 158);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.squareButton.setText("")
        self.squareButton.setObjectName("squareButton")
        self.layoutWidget = QtWidgets.QWidget(PowerControlDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 60, 101, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.triangUpButton = QtWidgets.QPushButton(self.layoutWidget)
        self.triangUpButton.setMinimumSize(QtCore.QSize(50, 50))
        self.triangUpButton.setStyleSheet("background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.triangUpButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/resources/Arriba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.triangUpButton.setIcon(icon)
        self.triangUpButton.setObjectName("triangUpButton")
        self.verticalLayout.addWidget(self.triangUpButton)
        self.triangDwnButton = QtWidgets.QPushButton(self.layoutWidget)
        self.triangDwnButton.setMinimumSize(QtCore.QSize(50, 50))
        self.triangDwnButton.setStyleSheet("background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.triangDwnButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/resources/Abajo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.triangDwnButton.setIcon(icon1)
        self.triangDwnButton.setObjectName("triangDwnButton")
        self.verticalLayout.addWidget(self.triangDwnButton)
        self.layoutWidget_2 = QtWidgets.QWidget(PowerControlDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(230, 190, 102, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.squareUpButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.squareUpButton.setMinimumSize(QtCore.QSize(50, 50))
        self.squareUpButton.setStyleSheet("background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.squareUpButton.setText("")
        self.squareUpButton.setIcon(icon)
        self.squareUpButton.setObjectName("squareUpButton")
        self.verticalLayout_2.addWidget(self.squareUpButton)
        self.squareDwnButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.squareDwnButton.setMinimumSize(QtCore.QSize(50, 50))
        self.squareDwnButton.setStyleSheet("background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.squareDwnButton.setText("")
        self.squareDwnButton.setIcon(icon1)
        self.squareDwnButton.setObjectName("squareDwnButton")
        self.verticalLayout_2.addWidget(self.squareDwnButton)
        self.layoutWidget_3 = QtWidgets.QWidget(PowerControlDialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(230, 340, 102, 131))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sinusUpButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.sinusUpButton.setMinimumSize(QtCore.QSize(50, 50))
        self.sinusUpButton.setStyleSheet("background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.sinusUpButton.setText("")
        self.sinusUpButton.setIcon(icon)
        self.sinusUpButton.setObjectName("sinusUpButton")
        self.verticalLayout_3.addWidget(self.sinusUpButton)
        self.sinusDwnButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.sinusDwnButton.setMinimumSize(QtCore.QSize(50, 50))
        self.sinusDwnButton.setStyleSheet("background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.sinusDwnButton.setText("")
        self.sinusDwnButton.setIcon(icon1)
        self.sinusDwnButton.setObjectName("sinusDwnButton")
        self.verticalLayout_3.addWidget(self.sinusDwnButton)
        self.label = QtWidgets.QLabel(PowerControlDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.triangLimitLabel = QtWidgets.QLabel(PowerControlDialog)
        self.triangLimitLabel.setGeometry(QtCore.QRect(140, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.triangLimitLabel.setFont(font)
        self.triangLimitLabel.setObjectName("triangLimitLabel")
        self.squareLimitLabel = QtWidgets.QLabel(PowerControlDialog)
        self.squareLimitLabel.setGeometry(QtCore.QRect(140, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.squareLimitLabel.setFont(font)
        self.squareLimitLabel.setObjectName("squareLimitLabel")
        self.sinusLimitLabel = QtWidgets.QLabel(PowerControlDialog)
        self.sinusLimitLabel.setGeometry(QtCore.QRect(140, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sinusLimitLabel.setFont(font)
        self.sinusLimitLabel.setObjectName("sinusLimitLabel")
        self.label_5 = QtWidgets.QLabel(PowerControlDialog)
        self.label_5.setGeometry(QtCore.QRect(390, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(PowerControlDialog)
        self.label_6.setGeometry(QtCore.QRect(350, 40, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.triangCurrLabel = QtWidgets.QLabel(PowerControlDialog)
        self.triangCurrLabel.setGeometry(QtCore.QRect(360, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.triangCurrLabel.setFont(font)
        self.triangCurrLabel.setObjectName("triangCurrLabel")
        self.squarePwr065Label = QtWidgets.QLabel(PowerControlDialog)
        self.squarePwr065Label.setGeometry(QtCore.QRect(480, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.squarePwr065Label.setFont(font)
        self.squarePwr065Label.setObjectName("squarePwr065Label")
        self.squareCurrLabel = QtWidgets.QLabel(PowerControlDialog)
        self.squareCurrLabel.setGeometry(QtCore.QRect(360, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.squareCurrLabel.setFont(font)
        self.squareCurrLabel.setObjectName("squareCurrLabel")
        self.doneButton = QtWidgets.QPushButton(PowerControlDialog)
        self.doneButton.setGeometry(QtCore.QRect(410, 451, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doneButton.setFont(font)
        self.doneButton.setObjectName("doneButton")
        self.triangPwr065Label = QtWidgets.QLabel(PowerControlDialog)
        self.triangPwr065Label.setGeometry(QtCore.QRect(480, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.triangPwr065Label.setFont(font)
        self.triangPwr065Label.setObjectName("triangPwr065Label")
        self.sinusPwr065Label = QtWidgets.QLabel(PowerControlDialog)
        self.sinusPwr065Label.setGeometry(QtCore.QRect(480, 350, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sinusPwr065Label.setFont(font)
        self.sinusPwr065Label.setObjectName("sinusPwr065Label")
        self.sinusCurrLabel = QtWidgets.QLabel(PowerControlDialog)
        self.sinusCurrLabel.setGeometry(QtCore.QRect(360, 350, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sinusCurrLabel.setFont(font)
        self.sinusCurrLabel.setObjectName("sinusCurrLabel")
        self.label_7 = QtWidgets.QLabel(PowerControlDialog)
        self.label_7.setGeometry(QtCore.QRect(480, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.squareTemp080Label = QtWidgets.QLabel(PowerControlDialog)
        self.squareTemp080Label.setGeometry(QtCore.QRect(670, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.squareTemp080Label.setFont(font)
        self.squareTemp080Label.setObjectName("squareTemp080Label")
        self.triangTemp065Label = QtWidgets.QLabel(PowerControlDialog)
        self.triangTemp065Label.setGeometry(QtCore.QRect(670, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.triangTemp065Label.setFont(font)
        self.triangTemp065Label.setObjectName("triangTemp065Label")
        self.triangTemp080Label = QtWidgets.QLabel(PowerControlDialog)
        self.triangTemp080Label.setGeometry(QtCore.QRect(670, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.triangTemp080Label.setFont(font)
        self.triangTemp080Label.setObjectName("triangTemp080Label")
        self.label_9 = QtWidgets.QLabel(PowerControlDialog)
        self.label_9.setGeometry(QtCore.QRect(570, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.sinusTemp080Label = QtWidgets.QLabel(PowerControlDialog)
        self.sinusTemp080Label.setGeometry(QtCore.QRect(670, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sinusTemp080Label.setFont(font)
        self.sinusTemp080Label.setObjectName("sinusTemp080Label")
        self.squareTemp065Label = QtWidgets.QLabel(PowerControlDialog)
        self.squareTemp065Label.setGeometry(QtCore.QRect(670, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.squareTemp065Label.setFont(font)
        self.squareTemp065Label.setObjectName("squareTemp065Label")
        self.sinusTemp065Label = QtWidgets.QLabel(PowerControlDialog)
        self.sinusTemp065Label.setGeometry(QtCore.QRect(670, 350, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sinusTemp065Label.setFont(font)
        self.sinusTemp065Label.setObjectName("sinusTemp065Label")
        self.sinusPwr080Label = QtWidgets.QLabel(PowerControlDialog)
        self.sinusPwr080Label.setGeometry(QtCore.QRect(480, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sinusPwr080Label.setFont(font)
        self.sinusPwr080Label.setObjectName("sinusPwr080Label")
        self.squarePwr080Label = QtWidgets.QLabel(PowerControlDialog)
        self.squarePwr080Label.setGeometry(QtCore.QRect(480, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.squarePwr080Label.setFont(font)
        self.squarePwr080Label.setObjectName("squarePwr080Label")
        self.triangPwr080Label = QtWidgets.QLabel(PowerControlDialog)
        self.triangPwr080Label.setGeometry(QtCore.QRect(480, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.triangPwr080Label.setFont(font)
        self.triangPwr080Label.setObjectName("triangPwr080Label")
        self.label_10 = QtWidgets.QLabel(PowerControlDialog)
        self.label_10.setGeometry(QtCore.QRect(570, 90, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(PowerControlDialog)
        self.label_8.setGeometry(QtCore.QRect(610, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(PowerControlDialog)
        QtCore.QMetaObject.connectSlotsByName(PowerControlDialog)

    def retranslateUi(self, PowerControlDialog):
        _translate = QtCore.QCoreApplication.translate
        PowerControlDialog.setWindowTitle(_translate("PowerControlDialog", "Dialog"))
        self.label.setText(_translate("PowerControlDialog", "Power Limits for signals:"))
        self.triangLimitLabel.setText(_translate("PowerControlDialog", "100%"))
        self.squareLimitLabel.setText(_translate("PowerControlDialog", "100%"))
        self.sinusLimitLabel.setText(_translate("PowerControlDialog", "100%"))
        self.label_5.setText(_translate("PowerControlDialog", "Estimated Results:"))
        self.label_6.setText(_translate("PowerControlDialog", "Irms [A]:"))
        self.triangCurrLabel.setText(_translate("PowerControlDialog", "100%"))
        self.squarePwr065Label.setText(_translate("PowerControlDialog", "100%"))
        self.squareCurrLabel.setText(_translate("PowerControlDialog", "100%"))
        self.doneButton.setText(_translate("PowerControlDialog", "Done!"))
        self.triangPwr065Label.setText(_translate("PowerControlDialog", "100%"))
        self.sinusPwr065Label.setText(_translate("PowerControlDialog", "100%"))
        self.sinusCurrLabel.setText(_translate("PowerControlDialog", "100%"))
        self.label_7.setText(_translate("PowerControlDialog", "Pwr [W]:"))
        self.squareTemp080Label.setText(_translate("PowerControlDialog", "100%"))
        self.triangTemp065Label.setText(_translate("PowerControlDialog", "100%"))
        self.triangTemp080Label.setText(_translate("PowerControlDialog", "100%"))
        self.label_9.setText(_translate("PowerControlDialog", "0.80mm"))
        self.sinusTemp080Label.setText(_translate("PowerControlDialog", "100%"))
        self.squareTemp065Label.setText(_translate("PowerControlDialog", "100%"))
        self.sinusTemp065Label.setText(_translate("PowerControlDialog", "100%"))
        self.sinusPwr080Label.setText(_translate("PowerControlDialog", "100%"))
        self.squarePwr080Label.setText(_translate("PowerControlDialog", "100%"))
        self.triangPwr080Label.setText(_translate("PowerControlDialog", "100%"))
        self.label_10.setText(_translate("PowerControlDialog", "0.65mm"))
        self.label_8.setText(_translate("PowerControlDialog", "Temp @ 30min [ºC]"))

import magnet3_res_rc
