# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wifi_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WiFiDialog(object):
    def setupUi(self, WiFiDialog):
        WiFiDialog.setObjectName("WiFiDialog")
        WiFiDialog.resize(1280, 800)
        WiFiDialog.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(WiFiDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(855, 20, 416, 316))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.minutesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.minutesLabel.setFont(font)
        self.minutesLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.minutesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.minutesLabel.setObjectName("minutesLabel")
        self.verticalLayout.addWidget(self.minutesLabel)
        self.wirelessLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wirelessLabel1.setFont(font)
        self.wirelessLabel1.setStyleSheet("color: rgb(55, 52, 53);")
        self.wirelessLabel1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wirelessLabel1.setObjectName("wirelessLabel1")
        self.verticalLayout.addWidget(self.wirelessLabel1)
        self.wirelessLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wirelessLabel2.setFont(font)
        self.wirelessLabel2.setStyleSheet("color: rgb(55, 52, 53);")
        self.wirelessLabel2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wirelessLabel2.setObjectName("wirelessLabel2")
        self.verticalLayout.addWidget(self.wirelessLabel2)
        self.wirelessLabel3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wirelessLabel3.setFont(font)
        self.wirelessLabel3.setStyleSheet("color: rgb(55, 52, 53);")
        self.wirelessLabel3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wirelessLabel3.setObjectName("wirelessLabel3")
        self.verticalLayout.addWidget(self.wirelessLabel3)
        self.ssidEdit = QtWidgets.QLineEdit(WiFiDialog)
        self.ssidEdit.setGeometry(QtCore.QRect(25, 200, 591, 76))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.ssidEdit.setFont(font)
        self.ssidEdit.setStyleSheet("color: rgb(55, 52, 53);")
        self.ssidEdit.setObjectName("ssidEdit")
        self.passEdit = QtWidgets.QLineEdit(WiFiDialog)
        self.passEdit.setGeometry(QtCore.QRect(25, 340, 591, 76))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.passEdit.setFont(font)
        self.passEdit.setStyleSheet("color: rgb(55, 52, 53);")
        self.passEdit.setObjectName("passEdit")
        self.comboBox = QtWidgets.QComboBox(WiFiDialog)
        self.comboBox.setGeometry(QtCore.QRect(25, 40, 591, 76))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color: rgb(55, 52, 53);")
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(WiFiDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(855, 350, 416, 316))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.minutesLabel_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.minutesLabel_5.setFont(font)
        self.minutesLabel_5.setStyleSheet("color: rgb(55, 52, 53);")
        self.minutesLabel_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.minutesLabel_5.setObjectName("minutesLabel_5")
        self.verticalLayout_2.addWidget(self.minutesLabel_5)
        self.wiredLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wiredLabel1.setFont(font)
        self.wiredLabel1.setStyleSheet("color: rgb(55, 52, 53);")
        self.wiredLabel1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wiredLabel1.setObjectName("wiredLabel1")
        self.verticalLayout_2.addWidget(self.wiredLabel1)
        self.wiredLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wiredLabel2.setFont(font)
        self.wiredLabel2.setStyleSheet("color: rgb(55, 52, 53);")
        self.wiredLabel2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wiredLabel2.setObjectName("wiredLabel2")
        self.verticalLayout_2.addWidget(self.wiredLabel2)
        self.wiredLabel3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wiredLabel3.setFont(font)
        self.wiredLabel3.setStyleSheet("color: rgb(55, 52, 53);")
        self.wiredLabel3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wiredLabel3.setObjectName("wiredLabel3")
        self.verticalLayout_2.addWidget(self.wiredLabel3)
        self.minutesLabel_9 = QtWidgets.QLabel(WiFiDialog)
        self.minutesLabel_9.setGeometry(QtCore.QRect(1005, 685, 191, 74))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.minutesLabel_9.setFont(font)
        self.minutesLabel_9.setStyleSheet("color: rgb(55, 52, 53);")
        self.minutesLabel_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.minutesLabel_9.setObjectName("minutesLabel_9")
        self.recheckLabel = QtWidgets.QLabel(WiFiDialog)
        self.recheckLabel.setGeometry(QtCore.QRect(1205, 685, 66, 74))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.recheckLabel.setFont(font)
        self.recheckLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.recheckLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.recheckLabel.setObjectName("recheckLabel")
        self.cancelButton = QtWidgets.QPushButton(WiFiDialog)
        self.cancelButton.setGeometry(QtCore.QRect(25, 470, 200, 100))
        self.cancelButton.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("background-color: rgb(240, 238, 126);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"color: rgb(55, 52, 53);")
        self.cancelButton.setObjectName("cancelButton")
        self.saveButton = QtWidgets.QPushButton(WiFiDialog)
        self.saveButton.setGeometry(QtCore.QRect(315, 470, 300, 100))
        self.saveButton.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("background-color: rgb(240, 238, 126);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"color: rgb(55, 52, 53);")
        self.saveButton.setObjectName("saveButton")
        self.scanButton = QtWidgets.QPushButton(WiFiDialog)
        self.scanButton.setGeometry(QtCore.QRect(635, 30, 200, 100))
        self.scanButton.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.scanButton.setFont(font)
        self.scanButton.setStyleSheet("background-color: rgb(240, 238, 126);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"color: rgb(55, 52, 53);")
        self.scanButton.setObjectName("scanButton")
        self.wirelessLabel2_2 = QtWidgets.QLabel(WiFiDialog)
        self.wirelessLabel2_2.setGeometry(QtCore.QRect(25, 140, 121, 56))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wirelessLabel2_2.setFont(font)
        self.wirelessLabel2_2.setStyleSheet("color: rgb(55, 52, 53);")
        self.wirelessLabel2_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wirelessLabel2_2.setObjectName("wirelessLabel2_2")
        self.wirelessLabel2_3 = QtWidgets.QLabel(WiFiDialog)
        self.wirelessLabel2_3.setGeometry(QtCore.QRect(25, 280, 201, 56))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.wirelessLabel2_3.setFont(font)
        self.wirelessLabel2_3.setStyleSheet("color: rgb(55, 52, 53);")
        self.wirelessLabel2_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wirelessLabel2_3.setObjectName("wirelessLabel2_3")
        self.passButton = QtWidgets.QPushButton(WiFiDialog)
        self.passButton.setGeometry(QtCore.QRect(25, 341, 591, 76))
        self.passButton.setStyleSheet("background-color: rgba(196, 255, 157, 0);\n"
"border: 0px\n"
"")
        self.passButton.setText("")
        self.passButton.setObjectName("passButton")
        self.ssidButton = QtWidgets.QPushButton(WiFiDialog)
        self.ssidButton.setGeometry(QtCore.QRect(25, 200, 591, 76))
        self.ssidButton.setStyleSheet("background-color: rgba(196, 255, 157, 0);\n"
"border: 0px\n"
"")
        self.ssidButton.setText("")
        self.ssidButton.setObjectName("ssidButton")
        self.waitLabel = QtWidgets.QLabel(WiFiDialog)
        self.waitLabel.setGeometry(QtCore.QRect(25, 605, 586, 56))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.waitLabel.setFont(font)
        self.waitLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.waitLabel.setText("")
        self.waitLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.waitLabel.setObjectName("waitLabel")

        self.retranslateUi(WiFiDialog)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(WiFiDialog)

    def retranslateUi(self, WiFiDialog):
        _translate = QtCore.QCoreApplication.translate
        WiFiDialog.setWindowTitle(_translate("WiFiDialog", "Dialog"))
        self.minutesLabel.setText(_translate("WiFiDialog", "Wireless Config:"))
        self.wirelessLabel1.setText(_translate("WiFiDialog", "Net:"))
        self.wirelessLabel2.setText(_translate("WiFiDialog", "Ip:"))
        self.wirelessLabel3.setText(_translate("WiFiDialog", "Gw:"))
        self.minutesLabel_5.setText(_translate("WiFiDialog", "Wired Config:"))
        self.wiredLabel1.setText(_translate("WiFiDialog", "Net:"))
        self.wiredLabel2.setText(_translate("WiFiDialog", "Ip:"))
        self.wiredLabel3.setText(_translate("WiFiDialog", "Gw:"))
        self.minutesLabel_9.setText(_translate("WiFiDialog", "Recheck in:"))
        self.recheckLabel.setText(_translate("WiFiDialog", "5"))
        self.cancelButton.setText(_translate("WiFiDialog", "Cancel"))
        self.saveButton.setText(_translate("WiFiDialog", "Save && Exit"))
        self.scanButton.setText(_translate("WiFiDialog", "Scan"))
        self.wirelessLabel2_2.setText(_translate("WiFiDialog", "SSID:"))
        self.wirelessLabel2_3.setText(_translate("WiFiDialog", "Password:"))

import wifi_res_rc
