# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stretcher_ver_2_0.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1261, 772))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.triangularButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triangularButton.sizePolicy().hasHeightForWidth())
        self.triangularButton.setSizePolicy(sizePolicy)
        self.triangularButton.setMinimumSize(QtCore.QSize(100, 100))
        self.triangularButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imag/resources/triangular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.triangularButton.setIcon(icon)
        self.triangularButton.setIconSize(QtCore.QSize(80, 80))
        self.triangularButton.setCheckable(True)
        self.triangularButton.setChecked(True)
        self.triangularButton.setObjectName("triangularButton")
        self.horizontalLayout.addWidget(self.triangularButton)
        self.cuadradaButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cuadradaButton.setMinimumSize(QtCore.QSize(100, 100))
        self.cuadradaButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imag/resources/cuadrada.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cuadradaButton.setIcon(icon1)
        self.cuadradaButton.setIconSize(QtCore.QSize(80, 80))
        self.cuadradaButton.setCheckable(True)
        self.cuadradaButton.setObjectName("cuadradaButton")
        self.horizontalLayout.addWidget(self.cuadradaButton)
        self.senoidalButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.senoidalButton.setMinimumSize(QtCore.QSize(100, 100))
        self.senoidalButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imag/resources/senoidal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.senoidalButton.setIcon(icon2)
        self.senoidalButton.setIconSize(QtCore.QSize(80, 80))
        self.senoidalButton.setCheckable(True)
        self.senoidalButton.setObjectName("senoidalButton")
        self.horizontalLayout.addWidget(self.senoidalButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.freq1Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.freq1Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.freq1Button.setFont(font)
        self.freq1Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.freq1Button.setCheckable(True)
        self.freq1Button.setChecked(True)
        self.freq1Button.setAutoExclusive(True)
        self.freq1Button.setObjectName("freq1Button")
        self.horizontalLayout.addWidget(self.freq1Button)
        self.freq2Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.freq2Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.freq2Button.setFont(font)
        self.freq2Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.freq2Button.setCheckable(True)
        self.freq2Button.setChecked(False)
        self.freq2Button.setAutoExclusive(True)
        self.freq2Button.setObjectName("freq2Button")
        self.horizontalLayout.addWidget(self.freq2Button)
        self.freq3Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.freq3Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.freq3Button.setFont(font)
        self.freq3Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.freq3Button.setCheckable(True)
        self.freq3Button.setChecked(False)
        self.freq3Button.setAutoExclusive(True)
        self.freq3Button.setObjectName("freq3Button")
        self.horizontalLayout.addWidget(self.freq3Button)
        self.freq4Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.freq4Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.freq4Button.setFont(font)
        self.freq4Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.freq4Button.setCheckable(True)
        self.freq4Button.setChecked(False)
        self.freq4Button.setAutoExclusive(True)
        self.freq4Button.setObjectName("freq4Button")
        self.horizontalLayout.addWidget(self.freq4Button)
        self.freq5Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.freq5Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.freq5Button.setFont(font)
        self.freq5Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.freq5Button.setCheckable(True)
        self.freq5Button.setAutoExclusive(True)
        self.freq5Button.setObjectName("freq5Button")
        self.horizontalLayout.addWidget(self.freq5Button)
        self.freq6Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.freq6Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.freq6Button.setFont(font)
        self.freq6Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.freq6Button.setCheckable(True)
        self.freq6Button.setAutoExclusive(True)
        self.freq6Button.setObjectName("freq6Button")
        self.horizontalLayout.addWidget(self.freq6Button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.updownButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updownButton.sizePolicy().hasHeightForWidth())
        self.updownButton.setSizePolicy(sizePolicy)
        self.updownButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.updownButton.setFont(font)
        self.updownButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.updownButton.setCheckable(False)
        self.updownButton.setChecked(False)
        self.updownButton.setObjectName("updownButton")
        self.horizontalLayout_5.addWidget(self.updownButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.ch1Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1Button.sizePolicy().hasHeightForWidth())
        self.ch1Button.setSizePolicy(sizePolicy)
        self.ch1Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ch1Button.setFont(font)
        self.ch1Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1Button.setCheckable(True)
        self.ch1Button.setChecked(True)
        self.ch1Button.setObjectName("ch1Button")
        self.horizontalLayout_5.addWidget(self.ch1Button)
        self.ch2Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2Button.sizePolicy().hasHeightForWidth())
        self.ch2Button.setSizePolicy(sizePolicy)
        self.ch2Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ch2Button.setFont(font)
        self.ch2Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch2Button.setCheckable(True)
        self.ch2Button.setChecked(True)
        self.ch2Button.setObjectName("ch2Button")
        self.horizontalLayout_5.addWidget(self.ch2Button)
        self.ch3Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch3Button.sizePolicy().hasHeightForWidth())
        self.ch3Button.setSizePolicy(sizePolicy)
        self.ch3Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ch3Button.setFont(font)
        self.ch3Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch3Button.setCheckable(True)
        self.ch3Button.setChecked(True)
        self.ch3Button.setObjectName("ch3Button")
        self.horizontalLayout_5.addWidget(self.ch3Button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.minutesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.minutesLabel.setFont(font)
        self.minutesLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.minutesLabel.setObjectName("minutesLabel")
        self.verticalLayout_5.addWidget(self.minutesLabel)
        self.timeStringLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeStringLabel.sizePolicy().hasHeightForWidth())
        self.timeStringLabel.setSizePolicy(sizePolicy)
        self.timeStringLabel.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeStringLabel.setFont(font)
        self.timeStringLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeStringLabel.setObjectName("timeStringLabel")
        self.verticalLayout_5.addWidget(self.timeStringLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.timeUpButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.timeUpButton.setMinimumSize(QtCore.QSize(100, 100))
        self.timeUpButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imag/resources/arrow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timeUpButton.setIcon(icon3)
        self.timeUpButton.setIconSize(QtCore.QSize(75, 75))
        self.timeUpButton.setObjectName("timeUpButton")
        self.verticalLayout_4.addWidget(self.timeUpButton)
        self.timeDwnButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.timeDwnButton.setMinimumSize(QtCore.QSize(100, 100))
        self.timeDwnButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imag/resources/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timeDwnButton.setIcon(icon4)
        self.timeDwnButton.setIconSize(QtCore.QSize(75, 75))
        self.timeDwnButton.setObjectName("timeDwnButton")
        self.verticalLayout_4.addWidget(self.timeDwnButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.powerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.powerLabel.setFont(font)
        self.powerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.powerLabel.setObjectName("powerLabel")
        self.verticalLayout_3.addWidget(self.powerLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.powerUpButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.powerUpButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerUpButton.setText("")
        self.powerUpButton.setIcon(icon3)
        self.powerUpButton.setIconSize(QtCore.QSize(75, 75))
        self.powerUpButton.setObjectName("powerUpButton")
        self.verticalLayout_2.addWidget(self.powerUpButton)
        self.powerDwnButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.powerDwnButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerDwnButton.setText("")
        self.powerDwnButton.setIcon(icon4)
        self.powerDwnButton.setIconSize(QtCore.QSize(75, 75))
        self.powerDwnButton.setObjectName("powerDwnButton")
        self.verticalLayout_2.addWidget(self.powerDwnButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.startButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.startButton.setFont(font)
        self.startButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startButton.setCheckable(False)
        self.startButton.setChecked(False)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_6.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.stopButton.setFont(font)
        self.stopButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stopButton.setCheckable(False)
        self.stopButton.setChecked(False)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_6.addWidget(self.stopButton)
        self.pauseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pauseButton.setFont(font)
        self.pauseButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pauseButton.setCheckable(False)
        self.pauseButton.setChecked(False)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_6.addWidget(self.pauseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.freq1Button.setText(_translate("Dialog", "7.83Hz"))
        self.freq2Button.setText(_translate("Dialog", "14.3Hz"))
        self.freq3Button.setText(_translate("Dialog", "20.8Hz"))
        self.freq4Button.setText(_translate("Dialog", "27.3Hz"))
        self.freq5Button.setText(_translate("Dialog", "33.8Hz"))
        self.freq6Button.setText(_translate("Dialog", "62.6Hz"))
        self.updownButton.setText(_translate("Dialog", "Up / Down"))
        self.ch1Button.setText(_translate("Dialog", "Channel 1"))
        self.ch2Button.setText(_translate("Dialog", "Channel 2"))
        self.ch3Button.setText(_translate("Dialog", "Channel 3"))
        self.minutesLabel.setText(_translate("Dialog", "30"))
        self.timeStringLabel.setText(_translate("Dialog", "minutes"))
        self.powerLabel.setText(_translate("Dialog", "100%"))
        self.startButton.setText(_translate("Dialog", "START"))
        self.stopButton.setText(_translate("Dialog", "STOP"))
        self.pauseButton.setText(_translate("Dialog", "PAUSE"))

import stretcher_res_rc
