# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lipo2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 600)
        Dialog.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"\n"
"")
        self.powerSlider = QtWidgets.QSlider(Dialog)
        self.powerSlider.setGeometry(QtCore.QRect(230, 120, 91, 251))
        self.powerSlider.setStyleSheet("QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"left: 4px; right: 4px;\n"
"border: 1px solid #bbb;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"height: 10px;\n"
"background: green;\n"
"margin: 0 -4px; /* expand outside the groove */\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"background: white;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"background: pink;\n"
"}")
        self.powerSlider.setMaximum(100)
        self.powerSlider.setOrientation(QtCore.Qt.Vertical)
        self.powerSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.powerSlider.setObjectName("powerSlider")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 400, 1001, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setMinimumSize(QtCore.QSize(300, 70))
        self.toolButton_4.setMaximumSize(QtCore.QSize(400, 70))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(30)
        font.setItalic(True)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/play2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_3.addWidget(self.toolButton_4)
        self.toolButton_6 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setMinimumSize(QtCore.QSize(300, 70))
        self.toolButton_6.setMaximumSize(QtCore.QSize(400, 70))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(30)
        font.setItalic(True)
        self.toolButton_6.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/stop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon1)
        self.toolButton_6.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_3.addWidget(self.toolButton_6)
        self.toolButton_5 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setMinimumSize(QtCore.QSize(300, 70))
        self.toolButton_5.setMaximumSize(QtCore.QSize(400, 70))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pause.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon2)
        self.toolButton_5.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_3.addWidget(self.toolButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ch1Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ch1Button.setObjectName("ch1Button")
        self.horizontalLayout_2.addWidget(self.ch1Button)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_2.addWidget(self.pushButton_14)
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(9, 9, 1001, 81))
        self.frame.setStyleSheet("QFrame {\n"
"/*background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.0539216 rgba(128, 128, 128, 255), stop:0.637255 rgba(255, 255, 255, 255));*/\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.0539216 rgba(51, 128, 128, 255), stop:0.637255 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QToolButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"background-color: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(970, 10, 21, 61))
        self.closeButton.setCheckable(True)
        self.closeButton.setObjectName("closeButton")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(20, 10, 81, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/continua.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon3)
        self.toolButton.setIconSize(QtCore.QSize(40, 40))
        self.toolButton.setCheckable(True)
        self.toolButton.setChecked(True)
        self.toolButton.setAutoExclusive(True)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(120, 10, 91, 61))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/pulsada.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_2.setCheckable(True)
        self.toolButton_2.setAutoExclusive(True)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(220, 10, 91, 61))
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_3.setCheckable(True)
        self.toolButton_3.setAutoExclusive(True)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(400, 10, 481, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/kirno_negro_cursiva.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Powerlabel = QtWidgets.QLabel(Dialog)
        self.Powerlabel.setGeometry(QtCore.QRect(9, 199, 141, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Powerlabel.sizePolicy().hasHeightForWidth())
        self.Powerlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.Powerlabel.setFont(font)
        self.Powerlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Powerlabel.setObjectName("Powerlabel")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 130, 101, 204))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pLevel1000 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel1000.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel1000.setText("")
        self.pLevel1000.setPixmap(QtGui.QPixmap(":/images/power_meter7.png"))
        self.pLevel1000.setObjectName("pLevel1000")
        self.verticalLayout_2.addWidget(self.pLevel1000)
        self.pLevel875 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel875.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel875.setText("")
        self.pLevel875.setPixmap(QtGui.QPixmap(":/images/power_meter6.png"))
        self.pLevel875.setObjectName("pLevel875")
        self.verticalLayout_2.addWidget(self.pLevel875)
        self.pLevel750 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel750.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel750.setText("")
        self.pLevel750.setPixmap(QtGui.QPixmap(":/images/power_meter5.png"))
        self.pLevel750.setObjectName("pLevel750")
        self.verticalLayout_2.addWidget(self.pLevel750)
        self.pLevel625 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel625.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel625.setText("")
        self.pLevel625.setPixmap(QtGui.QPixmap(":/images/power_meter4.png"))
        self.pLevel625.setScaledContents(False)
        self.pLevel625.setObjectName("pLevel625")
        self.verticalLayout_2.addWidget(self.pLevel625)
        self.pLevel500 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel500.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel500.setText("")
        self.pLevel500.setPixmap(QtGui.QPixmap(":/images/power_meter3b.png"))
        self.pLevel500.setObjectName("pLevel500")
        self.verticalLayout_2.addWidget(self.pLevel500)
        self.pLevel375 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel375.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel375.setText("")
        self.pLevel375.setPixmap(QtGui.QPixmap(":/images/power_meter3.png"))
        self.pLevel375.setObjectName("pLevel375")
        self.verticalLayout_2.addWidget(self.pLevel375)
        self.pLevel250 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel250.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel250.setText("")
        self.pLevel250.setPixmap(QtGui.QPixmap(":/images/power_meter0.png"))
        self.pLevel250.setScaledContents(False)
        self.pLevel250.setObjectName("pLevel250")
        self.verticalLayout_2.addWidget(self.pLevel250)
        self.pLevel125 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pLevel125.sizePolicy().hasHeightForWidth())
        self.pLevel125.setSizePolicy(sizePolicy)
        self.pLevel125.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel125.setText("")
        self.pLevel125.setPixmap(QtGui.QPixmap(":/images/power_meter0.png"))
        self.pLevel125.setScaledContents(False)
        self.pLevel125.setObjectName("pLevel125")
        self.verticalLayout_2.addWidget(self.pLevel125)
        self.Timerlabel = QtWidgets.QLabel(Dialog)
        self.Timerlabel.setGeometry(QtCore.QRect(540, 200, 71, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Timerlabel.sizePolicy().hasHeightForWidth())
        self.Timerlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.Timerlabel.setFont(font)
        self.Timerlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Timerlabel.setObjectName("Timerlabel")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(621, 131, 101, 204))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.m600 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m600.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m600.setText("")
        self.m600.setPixmap(QtGui.QPixmap(":/images/time_meter8.png"))
        self.m600.setObjectName("m600")
        self.verticalLayout_3.addWidget(self.m600)
        self.m525 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m525.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m525.setText("")
        self.m525.setPixmap(QtGui.QPixmap(":/images/time_meter7.png"))
        self.m525.setObjectName("m525")
        self.verticalLayout_3.addWidget(self.m525)
        self.m450 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m450.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m450.setText("")
        self.m450.setPixmap(QtGui.QPixmap(":/images/time_meter6.png"))
        self.m450.setObjectName("m450")
        self.verticalLayout_3.addWidget(self.m450)
        self.m375 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m375.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m375.setText("")
        self.m375.setPixmap(QtGui.QPixmap(":/images/time_meter5.png"))
        self.m375.setScaledContents(False)
        self.m375.setObjectName("m375")
        self.verticalLayout_3.addWidget(self.m375)
        self.m300 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m300.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m300.setText("")
        self.m300.setPixmap(QtGui.QPixmap(":/images/time_meter4.png"))
        self.m300.setObjectName("m300")
        self.verticalLayout_3.addWidget(self.m300)
        self.m225 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m225.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m225.setText("")
        self.m225.setPixmap(QtGui.QPixmap(":/images/time_meter3.png"))
        self.m225.setObjectName("m225")
        self.verticalLayout_3.addWidget(self.m225)
        self.m150 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m150.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m150.setText("")
        self.m150.setPixmap(QtGui.QPixmap(":/images/time_meter1.png"))
        self.m150.setScaledContents(False)
        self.m150.setObjectName("m150")
        self.verticalLayout_3.addWidget(self.m150)
        self.m75 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m75.sizePolicy().hasHeightForWidth())
        self.m75.setSizePolicy(sizePolicy)
        self.m75.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m75.setText("")
        self.m75.setPixmap(QtGui.QPixmap(":/images/time_meter1.png"))
        self.m75.setScaledContents(False)
        self.m75.setObjectName("m75")
        self.verticalLayout_3.addWidget(self.m75)
        self.Powerlabel_3 = QtWidgets.QLabel(Dialog)
        self.Powerlabel_3.setGeometry(QtCore.QRect(450, 260, 171, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Powerlabel_3.sizePolicy().hasHeightForWidth())
        self.Powerlabel_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Powerlabel_3.setFont(font)
        self.Powerlabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Powerlabel_3.setObjectName("Powerlabel_3")
        self.timerSlider = QtWidgets.QSlider(Dialog)
        self.timerSlider.setGeometry(QtCore.QRect(730, 120, 91, 251))
        self.timerSlider.setStyleSheet("QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"left: 4px; right: 4px;\n"
"border: 1px solid #bbb;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"height: 10px;\n"
"background: green;\n"
"margin: 0 -4px; /* expand outside the groove */\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"background: white;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"background: pink;\n"
"}")
        self.timerSlider.setMaximum(60)
        self.timerSlider.setOrientation(QtCore.Qt.Vertical)
        self.timerSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.timerSlider.setObjectName("timerSlider")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(840, 120, 171, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 151, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_4.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(380, 110, 91, 271))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/woman1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.powerSlider.raise_()
        self.verticalLayoutWidget.raise_()
        self.frame.raise_()
        self.Powerlabel.raise_()
        self.layoutWidget.raise_()
        self.Timerlabel.raise_()
        self.layoutWidget_2.raise_()
        self.timerSlider.raise_()
        self.groupBox.raise_()
        self.label_2.raise_()
        self.Powerlabel_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.toolButton_4.setText(_translate("Dialog", "  PLAY"))
        self.toolButton_6.setText(_translate("Dialog", "  STOP"))
        self.toolButton_5.setText(_translate("Dialog", "  PAUSE"))
        self.ch1Button.setText(_translate("Dialog", "PushButton"))
        self.pushButton_14.setText(_translate("Dialog", "PushButton"))
        self.pushButton_13.setText(_translate("Dialog", "PushButton"))
        self.pushButton_11.setText(_translate("Dialog", "PushButton"))
        self.pushButton_10.setText(_translate("Dialog", "PushButton"))
        self.pushButton_9.setText(_translate("Dialog", "PushButton"))
        self.pushButton_8.setText(_translate("Dialog", "PushButton"))
        self.pushButton_7.setText(_translate("Dialog", "PushButton"))
        self.closeButton.setText(_translate("Dialog", "CLOSE"))
        self.toolButton.setText(_translate("Dialog", "Continua"))
        self.toolButton_2.setText(_translate("Dialog", "Pulsada"))
        self.toolButton_3.setText(_translate("Dialog", "Modulada"))
        self.Powerlabel.setText(_translate("Dialog", "0%"))
        self.Timerlabel.setText(_translate("Dialog", "0"))
        self.Powerlabel_3.setText(_translate("Dialog", "minutos"))
        self.groupBox.setTitle(_translate("Dialog", "Alarmas Intermedias"))
        self.radioButton.setText(_translate("Dialog", "Nin&guna"))
        self.radioButton_3.setText(_translate("Dialog", "&Una"))
        self.radioButton_4.setText(_translate("Dialog", "&Dos"))
        self.radioButton_2.setText(_translate("Dialog", "Cua&tro"))

import res_lipo2_rc
