# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lipo3_800_480.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 480)
        Dialog.setStyleSheet("background-color: rgb(85, 170, 127); /*este es el verde de siempre*/\n"
"/*background-color: rgb(173, 127, 168); este es el violeta*/\n"
"")
        self.powerSlider = QtWidgets.QSlider(Dialog)
        self.powerSlider.setGeometry(QtCore.QRect(190, 80, 91, 201))
        self.powerSlider.setStyleSheet("QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"left: 4px; right: 4px;\n"
"border: 1px solid #bbb;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"height: 30px;\n"
"background: rgb(13, 10, 61);\n"
"margin: 0 -4px; /* expand outside the groove */\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"background: rgb(32, 74, 135);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"background: rgb(110, 202, 206);\n"
"}")
        self.powerSlider.setMaximum(100)
        self.powerSlider.setOrientation(QtCore.Qt.Vertical)
        self.powerSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.powerSlider.setObjectName("powerSlider")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 300, 781, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(234, 70))
        self.playButton.setMaximumSize(QtCore.QSize(400, 70))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(30)
        font.setItalic(True)
        self.playButton.setFont(font)
        self.playButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.playButton.setStyleSheet("background-color: rgb(114, 159, 207);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/play2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(48, 48))
        self.playButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_3.addWidget(self.playButton)
        self.stopButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(234, 70))
        self.stopButton.setMaximumSize(QtCore.QSize(400, 70))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(30)
        font.setItalic(True)
        self.stopButton.setFont(font)
        self.stopButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/stop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setIconSize(QtCore.QSize(48, 48))
        self.stopButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_3.addWidget(self.stopButton)
        self.pauseButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMinimumSize(QtCore.QSize(234, 70))
        self.pauseButton.setMaximumSize(QtCore.QSize(400, 70))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pauseButton.setFont(font)
        self.pauseButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pauseButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/pause.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon2)
        self.pauseButton.setIconSize(QtCore.QSize(48, 48))
        self.pauseButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_3.addWidget(self.pauseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ch1Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1Button.sizePolicy().hasHeightForWidth())
        self.ch1Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch1Button.setFont(font)
        self.ch1Button.setStyleSheet("")
        self.ch1Button.setObjectName("ch1Button")
        self.horizontalLayout_2.addWidget(self.ch1Button)
        self.ch2Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2Button.sizePolicy().hasHeightForWidth())
        self.ch2Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch2Button.setFont(font)
        self.ch2Button.setStyleSheet("")
        self.ch2Button.setObjectName("ch2Button")
        self.horizontalLayout_2.addWidget(self.ch2Button)
        self.ch3Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch3Button.sizePolicy().hasHeightForWidth())
        self.ch3Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch3Button.setFont(font)
        self.ch3Button.setStyleSheet("")
        self.ch3Button.setObjectName("ch3Button")
        self.horizontalLayout_2.addWidget(self.ch3Button)
        self.ch4Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch4Button.sizePolicy().hasHeightForWidth())
        self.ch4Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch4Button.setFont(font)
        self.ch4Button.setStyleSheet("")
        self.ch4Button.setObjectName("ch4Button")
        self.horizontalLayout_2.addWidget(self.ch4Button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ch5Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch5Button.sizePolicy().hasHeightForWidth())
        self.ch5Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch5Button.setFont(font)
        self.ch5Button.setStyleSheet("")
        self.ch5Button.setObjectName("ch5Button")
        self.horizontalLayout_2.addWidget(self.ch5Button)
        self.ch6Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch6Button.sizePolicy().hasHeightForWidth())
        self.ch6Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch6Button.setFont(font)
        self.ch6Button.setStyleSheet("")
        self.ch6Button.setObjectName("ch6Button")
        self.horizontalLayout_2.addWidget(self.ch6Button)
        self.ch7Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch7Button.sizePolicy().hasHeightForWidth())
        self.ch7Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch7Button.setFont(font)
        self.ch7Button.setStyleSheet("")
        self.ch7Button.setObjectName("ch7Button")
        self.horizontalLayout_2.addWidget(self.ch7Button)
        self.ch8Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch8Button.sizePolicy().hasHeightForWidth())
        self.ch8Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ch8Button.setFont(font)
        self.ch8Button.setStyleSheet("")
        self.ch8Button.setObjectName("ch8Button")
        self.horizontalLayout_2.addWidget(self.ch8Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 799, 64))
        self.frame.setStyleSheet("QFrame {\n"
"/*background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.0539216 rgba(128, 128, 128, 255), stop:0.637255 rgba(255, 255, 255, 255));*/\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.0539216 rgba(51, 128, 128, 255), stop:0.637255 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QToolButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"background-color: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cwaveButton = QtWidgets.QToolButton(self.frame)
        self.cwaveButton.setGeometry(QtCore.QRect(10, 7, 71, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/continua.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cwaveButton.setIcon(icon3)
        self.cwaveButton.setIconSize(QtCore.QSize(26, 26))
        self.cwaveButton.setCheckable(True)
        self.cwaveButton.setChecked(True)
        self.cwaveButton.setAutoExclusive(True)
        self.cwaveButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.cwaveButton.setObjectName("cwaveButton")
        self.pulsedButton = QtWidgets.QToolButton(self.frame)
        self.pulsedButton.setGeometry(QtCore.QRect(90, 7, 71, 51))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/pulsada.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pulsedButton.setIcon(icon4)
        self.pulsedButton.setIconSize(QtCore.QSize(28, 28))
        self.pulsedButton.setCheckable(True)
        self.pulsedButton.setAutoExclusive(True)
        self.pulsedButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pulsedButton.setObjectName("pulsedButton")
        self.modulatedButton = QtWidgets.QToolButton(self.frame)
        self.modulatedButton.setGeometry(QtCore.QRect(170, 10, 71, 51))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/modulada.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modulatedButton.setIcon(icon5)
        self.modulatedButton.setIconSize(QtCore.QSize(28, 28))
        self.modulatedButton.setCheckable(True)
        self.modulatedButton.setAutoExclusive(True)
        self.modulatedButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.modulatedButton.setObjectName("modulatedButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(370, 10, 391, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/resources/kirno_negro_cursiva.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.freqButton = QtWidgets.QToolButton(self.frame)
        self.freqButton.setGeometry(QtCore.QRect(250, 10, 81, 51))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.freqButton.setFont(font)
        self.freqButton.setIconSize(QtCore.QSize(32, 32))
        self.freqButton.setCheckable(False)
        self.freqButton.setAutoExclusive(False)
        self.freqButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.freqButton.setObjectName("freqButton")
        self.Powerlabel = QtWidgets.QLabel(Dialog)
        self.Powerlabel.setGeometry(QtCore.QRect(0, 130, 131, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Powerlabel.sizePolicy().hasHeightForWidth())
        self.Powerlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.Powerlabel.setFont(font)
        self.Powerlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Powerlabel.setObjectName("Powerlabel")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 80, 91, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pLevel1000 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel1000.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel1000.setText("")
        self.pLevel1000.setPixmap(QtGui.QPixmap(":/images/resources/power_meter7.png"))
        self.pLevel1000.setObjectName("pLevel1000")
        self.verticalLayout_2.addWidget(self.pLevel1000)
        self.pLevel875 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel875.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel875.setText("")
        self.pLevel875.setPixmap(QtGui.QPixmap(":/images/resources/power_meter6.png"))
        self.pLevel875.setObjectName("pLevel875")
        self.verticalLayout_2.addWidget(self.pLevel875)
        self.pLevel750 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel750.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel750.setText("")
        self.pLevel750.setPixmap(QtGui.QPixmap(":/images/resources/power_meter5.png"))
        self.pLevel750.setObjectName("pLevel750")
        self.verticalLayout_2.addWidget(self.pLevel750)
        self.pLevel625 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel625.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel625.setText("")
        self.pLevel625.setPixmap(QtGui.QPixmap(":/images/resources/power_meter4.png"))
        self.pLevel625.setScaledContents(False)
        self.pLevel625.setObjectName("pLevel625")
        self.verticalLayout_2.addWidget(self.pLevel625)
        self.pLevel500 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel500.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel500.setText("")
        self.pLevel500.setPixmap(QtGui.QPixmap(":/images/resources/power_meter3b.png"))
        self.pLevel500.setObjectName("pLevel500")
        self.verticalLayout_2.addWidget(self.pLevel500)
        self.pLevel375 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel375.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel375.setText("")
        self.pLevel375.setPixmap(QtGui.QPixmap(":/images/resources/power_meter3.png"))
        self.pLevel375.setObjectName("pLevel375")
        self.verticalLayout_2.addWidget(self.pLevel375)
        self.pLevel250 = QtWidgets.QLabel(self.layoutWidget)
        self.pLevel250.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel250.setText("")
        self.pLevel250.setPixmap(QtGui.QPixmap(":/images/resources/power_meter0.png"))
        self.pLevel250.setScaledContents(False)
        self.pLevel250.setObjectName("pLevel250")
        self.verticalLayout_2.addWidget(self.pLevel250)
        self.pLevel125 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pLevel125.sizePolicy().hasHeightForWidth())
        self.pLevel125.setSizePolicy(sizePolicy)
        self.pLevel125.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pLevel125.setText("")
        self.pLevel125.setPixmap(QtGui.QPixmap(":/images/resources/power_meter0.png"))
        self.pLevel125.setScaledContents(False)
        self.pLevel125.setObjectName("pLevel125")
        self.verticalLayout_2.addWidget(self.pLevel125)
        self.Timerlabel = QtWidgets.QLabel(Dialog)
        self.Timerlabel.setGeometry(QtCore.QRect(360, 130, 141, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Timerlabel.sizePolicy().hasHeightForWidth())
        self.Timerlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.Timerlabel.setFont(font)
        self.Timerlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Timerlabel.setObjectName("Timerlabel")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(490, 80, 101, 204))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.m600 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m600.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m600.setText("")
        self.m600.setPixmap(QtGui.QPixmap(":/images/resources/time_meter8.png"))
        self.m600.setObjectName("m600")
        self.verticalLayout_3.addWidget(self.m600)
        self.m525 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m525.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m525.setText("")
        self.m525.setPixmap(QtGui.QPixmap(":/images/resources/time_meter7.png"))
        self.m525.setObjectName("m525")
        self.verticalLayout_3.addWidget(self.m525)
        self.m450 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m450.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m450.setText("")
        self.m450.setPixmap(QtGui.QPixmap(":/images/resources/time_meter6.png"))
        self.m450.setObjectName("m450")
        self.verticalLayout_3.addWidget(self.m450)
        self.m375 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m375.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m375.setText("")
        self.m375.setPixmap(QtGui.QPixmap(":/images/resources/time_meter5.png"))
        self.m375.setScaledContents(False)
        self.m375.setObjectName("m375")
        self.verticalLayout_3.addWidget(self.m375)
        self.m300 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m300.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m300.setText("")
        self.m300.setPixmap(QtGui.QPixmap(":/images/resources/time_meter4.png"))
        self.m300.setObjectName("m300")
        self.verticalLayout_3.addWidget(self.m300)
        self.m225 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m225.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m225.setText("")
        self.m225.setPixmap(QtGui.QPixmap(":/images/resources/time_meter3.png"))
        self.m225.setObjectName("m225")
        self.verticalLayout_3.addWidget(self.m225)
        self.m150 = QtWidgets.QLabel(self.layoutWidget_2)
        self.m150.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m150.setText("")
        self.m150.setPixmap(QtGui.QPixmap(":/images/resources/time_meter1.png"))
        self.m150.setScaledContents(False)
        self.m150.setObjectName("m150")
        self.verticalLayout_3.addWidget(self.m150)
        self.m75 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m75.sizePolicy().hasHeightForWidth())
        self.m75.setSizePolicy(sizePolicy)
        self.m75.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.m75.setText("")
        self.m75.setPixmap(QtGui.QPixmap(":/images/resources/time_meter1.png"))
        self.m75.setScaledContents(False)
        self.m75.setObjectName("m75")
        self.verticalLayout_3.addWidget(self.m75)
        self.unitlabel = QtWidgets.QLabel(Dialog)
        self.unitlabel.setGeometry(QtCore.QRect(340, 190, 181, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitlabel.sizePolicy().hasHeightForWidth())
        self.unitlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.unitlabel.setFont(font)
        self.unitlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.unitlabel.setObjectName("unitlabel")
        self.timerSlider = QtWidgets.QSlider(Dialog)
        self.timerSlider.setGeometry(QtCore.QRect(590, 80, 91, 201))
        self.timerSlider.setStyleSheet("QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"left: 4px; right: 4px;\n"
"border: 1px solid #bbb;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"height: 30px;\n"
"background: rgb(13, 10, 61);\n"
"margin: 0 -4px; /* expand outside the groove */\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"background: rgb(32, 74, 135);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"background: rgb(110, 202, 206);\n"
"}")
        self.timerSlider.setMaximum(60)
        self.timerSlider.setOrientation(QtCore.Qt.Vertical)
        self.timerSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.timerSlider.setObjectName("timerSlider")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(680, 101, 111, 181))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 101, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.alarmButton_none = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.alarmButton_none.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alarmButton_none.setFont(font)
        self.alarmButton_none.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"/*border: none;*/\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"")
        self.alarmButton_none.setCheckable(True)
        self.alarmButton_none.setAutoExclusive(True)
        self.alarmButton_none.setObjectName("alarmButton_none")
        self.verticalLayout_4.addWidget(self.alarmButton_none)
        self.alarmButton_one = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.alarmButton_one.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alarmButton_one.setFont(font)
        self.alarmButton_one.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"/*border: none;*/\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"")
        self.alarmButton_one.setCheckable(True)
        self.alarmButton_one.setAutoExclusive(True)
        self.alarmButton_one.setObjectName("alarmButton_one")
        self.verticalLayout_4.addWidget(self.alarmButton_one)
        self.alarmButton_two = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.alarmButton_two.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alarmButton_two.setFont(font)
        self.alarmButton_two.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"/*border: none;*/\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"")
        self.alarmButton_two.setCheckable(True)
        self.alarmButton_two.setAutoExclusive(True)
        self.alarmButton_two.setObjectName("alarmButton_two")
        self.verticalLayout_4.addWidget(self.alarmButton_two)
        self.alarmButton_four = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.alarmButton_four.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alarmButton_four.setFont(font)
        self.alarmButton_four.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"/*border: none;*/\n"
"border: 1px solid #777;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:checked, QPushButton:pressed {\n"
"background-color: rgb(170, 170, 255);\n"
"}\n"
"")
        self.alarmButton_four.setCheckable(True)
        self.alarmButton_four.setAutoExclusive(True)
        self.alarmButton_four.setObjectName("alarmButton_four")
        self.verticalLayout_4.addWidget(self.alarmButton_four)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 80, 61, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/resources/woman1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(680, 80, 111, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.powerSlider.raise_()
        self.verticalLayoutWidget.raise_()
        self.frame.raise_()
        self.Powerlabel.raise_()
        self.layoutWidget.raise_()
        self.Timerlabel.raise_()
        self.layoutWidget_2.raise_()
        self.timerSlider.raise_()
        self.groupBox.raise_()
        self.label_2.raise_()
        self.unitlabel.raise_()
        self.label_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.playButton.setText(_translate("Dialog", "  PLAY"))
        self.stopButton.setText(_translate("Dialog", "  STOP"))
        self.pauseButton.setText(_translate("Dialog", "  PAUSE"))
        self.ch1Button.setText(_translate("Dialog", "CH1"))
        self.ch2Button.setText(_translate("Dialog", "CH2"))
        self.ch3Button.setText(_translate("Dialog", "CH3"))
        self.ch4Button.setText(_translate("Dialog", "CH4"))
        self.ch5Button.setText(_translate("Dialog", "CH5"))
        self.ch6Button.setText(_translate("Dialog", "CH6"))
        self.ch7Button.setText(_translate("Dialog", "CH7"))
        self.ch8Button.setText(_translate("Dialog", "CH8"))
        self.cwaveButton.setText(_translate("Dialog", "Continua"))
        self.pulsedButton.setText(_translate("Dialog", "Pulsada"))
        self.modulatedButton.setText(_translate("Dialog", "Modulada"))
        self.freqButton.setText(_translate("Dialog", "Frecuencia"))
        self.Powerlabel.setText(_translate("Dialog", "100%"))
        self.Timerlabel.setText(_translate("Dialog", "0"))
        self.unitlabel.setText(_translate("Dialog", "minutos"))
        self.groupBox.setTitle(_translate("Dialog", "  Intermedias"))
        self.alarmButton_none.setText(_translate("Dialog", "NINGUNA"))
        self.alarmButton_one.setText(_translate("Dialog", "UNA"))
        self.alarmButton_two.setText(_translate("Dialog", "DOS"))
        self.alarmButton_four.setText(_translate("Dialog", "CUATRO"))
        self.label_3.setText(_translate("Dialog", "  Alarmas"))

import res_lipo2_rc
