# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magnet_ver_3_1.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 800)
        Dialog.setStyleSheet("QDialog {\n"
"background-image: url(:/background/resources/background_magnet_02.png);\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(54, 350, 346, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(22)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.freq1Button = QtWidgets.QPushButton(self.layoutWidget)
        self.freq1Button.setMinimumSize(QtCore.QSize(100, 100))
        self.freq1Button.setStyleSheet("background-image: url(:/frequencies/resources/7_83Hz.png);\n"
"background-color: rgb(240, 231, 240);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.freq1Button.setText("")
        self.freq1Button.setObjectName("freq1Button")
        self.horizontalLayout_2.addWidget(self.freq1Button)
        self.freq2Button = QtWidgets.QPushButton(self.layoutWidget)
        self.freq2Button.setMinimumSize(QtCore.QSize(100, 100))
        self.freq2Button.setStyleSheet("background-image: url(:/frequencies/resources/11_79Hz.png);\n"
"background-color: rgb(230, 217, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.freq2Button.setText("")
        self.freq2Button.setObjectName("freq2Button")
        self.horizontalLayout_2.addWidget(self.freq2Button)
        self.freq3Button = QtWidgets.QPushButton(self.layoutWidget)
        self.freq3Button.setMinimumSize(QtCore.QSize(100, 100))
        self.freq3Button.setStyleSheet("background-image: url(:/frequencies/resources/16_67Hz.png);\n"
"background-color: rgb(221, 202, 222);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.freq3Button.setText("")
        self.freq3Button.setObjectName("freq3Button")
        self.horizontalLayout_2.addWidget(self.freq3Button)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(54, 460, 346, 102))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(22)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.freq4Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.freq4Button.setMinimumSize(QtCore.QSize(100, 100))
        self.freq4Button.setStyleSheet("background-image: url(:/frequencies/resources/23_58Hz.png);\n"
"background-color: rgb(211, 187, 213);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.freq4Button.setText("")
        self.freq4Button.setObjectName("freq4Button")
        self.horizontalLayout_3.addWidget(self.freq4Button)
        self.freq5Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.freq5Button.setMinimumSize(QtCore.QSize(100, 100))
        self.freq5Button.setStyleSheet("background-image: url(:/frequencies/resources/30_80Hz.png);\n"
"background-color: rgb(202, 173, 204);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.freq5Button.setText("")
        self.freq5Button.setObjectName("freq5Button")
        self.horizontalLayout_3.addWidget(self.freq5Button)
        self.freq6Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.freq6Button.setMinimumSize(QtCore.QSize(100, 100))
        self.freq6Button.setStyleSheet("background-image: url(:/frequencies/resources/62_64Hz.png);\n"
"background-color: rgb(196, 161, 203);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.freq6Button.setText("")
        self.freq6Button.setObjectName("freq6Button")
        self.horizontalLayout_3.addWidget(self.freq6Button)
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(646, 260, 102, 224))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(22)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.min30Button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.min30Button.setMinimumSize(QtCore.QSize(100, 100))
        self.min30Button.setStyleSheet("background-image: url(:/buttons/resources/30min.png);\n"
"background-color: rgb(221, 235, 242);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.min30Button.setText("")
        self.min30Button.setObjectName("min30Button")
        self.verticalLayout_2.addWidget(self.min30Button)
        self.min45Button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.min45Button.setMinimumSize(QtCore.QSize(100, 100))
        self.min45Button.setStyleSheet("background-image: url(:/buttons/resources/40min.png);\n"
"background-color: rgb(191, 218, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.min45Button.setText("")
        self.min45Button.setObjectName("min45Button")
        self.verticalLayout_2.addWidget(self.min45Button)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(766, 260, 102, 224))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(22)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.timeUpButton = QtWidgets.QPushButton(self.layoutWidget_4)
        self.timeUpButton.setMinimumSize(QtCore.QSize(100, 100))
        self.timeUpButton.setStyleSheet("background-image: url(:/buttons/resources/Arriba.png);\n"
"background-color: rgb(138, 186, 210);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.timeUpButton.setText("")
        self.timeUpButton.setObjectName("timeUpButton")
        self.verticalLayout_3.addWidget(self.timeUpButton)
        self.timeDwnButton = QtWidgets.QPushButton(self.layoutWidget_4)
        self.timeDwnButton.setMinimumSize(QtCore.QSize(100, 100))
        self.timeDwnButton.setStyleSheet("background-image: url(:/buttons/resources/Abajo.png);\n"
"background-color: rgb(242, 248, 250);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.timeDwnButton.setText("")
        self.timeDwnButton.setObjectName("timeDwnButton")
        self.verticalLayout_3.addWidget(self.timeDwnButton)
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(80, 630, 300, 120))
        self.startButton.setMinimumSize(QtCore.QSize(100, 100))
        self.startButton.setStyleSheet("background-image: url(:/buttons/resources/Play.png);\n"
"background-color: rgb(245, 245, 245);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.startButton.setText("")
        self.startButton.setObjectName("startButton")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(54, 150, 346, 102))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(22)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.triangularButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.triangularButton.setMinimumSize(QtCore.QSize(100, 100))
        self.triangularButton.setStyleSheet("background-image: url(:/buttons/resources/Triangular.png);\n"
"background-color: rgb(248, 247, 190);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.triangularButton.setText("")
        self.triangularButton.setObjectName("triangularButton")
        self.horizontalLayout.addWidget(self.triangularButton)
        self.squareButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.squareButton.setMinimumSize(QtCore.QSize(100, 100))
        self.squareButton.setStyleSheet("background-image: url(:/buttons/resources/Cuadrada.png);\n"
"background-color: rgb(244, 243, 158);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.squareButton.setText("")
        self.squareButton.setObjectName("squareButton")
        self.horizontalLayout.addWidget(self.squareButton)
        self.sinusoidalButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.sinusoidalButton.setMinimumSize(QtCore.QSize(100, 100))
        self.sinusoidalButton.setStyleSheet("background-image: url(:/buttons/resources/Sinus.png);\n"
"background-color: rgb(240, 238, 126);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.sinusoidalButton.setText("")
        self.sinusoidalButton.setObjectName("sinusoidalButton")
        self.horizontalLayout.addWidget(self.sinusoidalButton)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(470, 260, 102, 224))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.powerUpButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.powerUpButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerUpButton.setStyleSheet("background-image: url(:/buttons/resources/Arriba.png);\n"
"background-color: rgb(208, 165, 156);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerUpButton.setText("")
        self.powerUpButton.setObjectName("powerUpButton")
        self.verticalLayout.addWidget(self.powerUpButton)
        self.powerDwnButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.powerDwnButton.setMinimumSize(QtCore.QSize(100, 100))
        self.powerDwnButton.setStyleSheet("background-image: url(:/buttons/resources/Abajo.png);\n"
"background-color: rgb(244, 233, 231);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.powerDwnButton.setText("")
        self.powerDwnButton.setObjectName("powerDwnButton")
        self.verticalLayout.addWidget(self.powerDwnButton)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(938, 140, 102, 346))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mem1Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.mem1Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.mem1Button.setFont(font)
        self.mem1Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mem1Button.setStyleSheet("color: rgb(55, 52, 53);\n"
"background-color: rgb(255, 244, 230);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.mem1Button.setObjectName("mem1Button")
        self.verticalLayout_4.addWidget(self.mem1Button)
        self.mem2Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.mem2Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.mem2Button.setFont(font)
        self.mem2Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mem2Button.setStyleSheet("color: rgb(55, 52, 53);\n"
"background-color: rgb(255, 232, 204);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.mem2Button.setObjectName("mem2Button")
        self.verticalLayout_4.addWidget(self.mem2Button)
        self.mem3Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.mem3Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.mem3Button.setFont(font)
        self.mem3Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mem3Button.setStyleSheet("color: rgb(55, 52, 53);\n"
"background-color: rgb(255, 221, 179);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);")
        self.mem3Button.setObjectName("mem3Button")
        self.verticalLayout_4.addWidget(self.mem3Button)
        self.layoutWidget4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(1058, 160, 171, 305))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(30)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mem11Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem11Label.setFont(font)
        self.mem11Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem11Label.setObjectName("mem11Label")
        self.verticalLayout_5.addWidget(self.mem11Label)
        self.mem12Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem12Label.setFont(font)
        self.mem12Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem12Label.setObjectName("mem12Label")
        self.verticalLayout_5.addWidget(self.mem12Label)
        self.mem13Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem13Label.setFont(font)
        self.mem13Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem13Label.setObjectName("mem13Label")
        self.verticalLayout_5.addWidget(self.mem13Label)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mem21Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem21Label.setFont(font)
        self.mem21Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem21Label.setObjectName("mem21Label")
        self.verticalLayout_6.addWidget(self.mem21Label)
        self.mem22Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem22Label.setFont(font)
        self.mem22Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem22Label.setObjectName("mem22Label")
        self.verticalLayout_6.addWidget(self.mem22Label)
        self.mem23Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem23Label.setFont(font)
        self.mem23Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem23Label.setObjectName("mem23Label")
        self.verticalLayout_6.addWidget(self.mem23Label)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mem31Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem31Label.setFont(font)
        self.mem31Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem31Label.setObjectName("mem31Label")
        self.verticalLayout_7.addWidget(self.mem31Label)
        self.mem32Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem32Label.setFont(font)
        self.mem32Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem32Label.setObjectName("mem32Label")
        self.verticalLayout_7.addWidget(self.mem32Label)
        self.mem33Label = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mem33Label.setFont(font)
        self.mem33Label.setStyleSheet("color: rgb(55, 52, 53);")
        self.mem33Label.setObjectName("mem33Label")
        self.verticalLayout_7.addWidget(self.mem33Label)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.minutesLabel = QtWidgets.QLabel(Dialog)
        self.minutesLabel.setGeometry(QtCore.QRect(640, 170, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.minutesLabel.setFont(font)
        self.minutesLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.minutesLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.minutesLabel.setObjectName("minutesLabel")
        self.powerLabel = QtWidgets.QLabel(Dialog)
        self.powerLabel.setGeometry(QtCore.QRect(465, 150, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.powerLabel.setFont(font)
        self.powerLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.powerLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.powerLabel.setObjectName("powerLabel")
        self.date_timeLabel = QtWidgets.QLabel(Dialog)
        self.date_timeLabel.setGeometry(QtCore.QRect(910, 40, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.date_timeLabel.setFont(font)
        self.date_timeLabel.setStyleSheet("color: rgb(55, 52, 53);")
        self.date_timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_timeLabel.setObjectName("date_timeLabel")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(453, 649, 791, 116))
        self.textEdit.setStyleSheet("border:2px outset;\n"
"background-color: rgb(246, 255, 254);\n"
"border-radius: 16px;\n"
"color: rgb(0, 0, 127);\n"
"border-color: rgb(55, 52, 53);")
        self.textEdit.setObjectName("textEdit")
        self.diagButton = QtWidgets.QPushButton(Dialog)
        self.diagButton.setGeometry(QtCore.QRect(90, 30, 141, 41))
        self.diagButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px")
        self.diagButton.setText("")
        self.diagButton.setObjectName("diagButton")
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(630, 525, 596, 102))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(22)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ch1Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1Button.sizePolicy().hasHeightForWidth())
        self.ch1Button.setSizePolicy(sizePolicy)
        self.ch1Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch1Button.setFont(font)
        self.ch1Button.setStyleSheet("background-color: rgb(157, 211, 175);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch1Button.setObjectName("ch1Button")
        self.horizontalLayout_4.addWidget(self.ch1Button)
        self.ch2Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2Button.sizePolicy().hasHeightForWidth())
        self.ch2Button.setSizePolicy(sizePolicy)
        self.ch2Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch2Button.setFont(font)
        self.ch2Button.setStyleSheet("background-color: rgb(157, 211, 175);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch2Button.setObjectName("ch2Button")
        self.horizontalLayout_4.addWidget(self.ch2Button)
        self.ch3Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch3Button.sizePolicy().hasHeightForWidth())
        self.ch3Button.setSizePolicy(sizePolicy)
        self.ch3Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch3Button.setFont(font)
        self.ch3Button.setStyleSheet("background-color: rgb(157, 211, 175);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch3Button.setObjectName("ch3Button")
        self.horizontalLayout_4.addWidget(self.ch3Button)
        self.ch4Button = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch4Button.sizePolicy().hasHeightForWidth())
        self.ch4Button.setSizePolicy(sizePolicy)
        self.ch4Button.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch4Button.setFont(font)
        self.ch4Button.setStyleSheet("background-color: rgb(157, 211, 175);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(55, 52, 53);\n"
"text-align:top;\n"
"color: rgb(55, 52, 53);")
        self.ch4Button.setObjectName("ch4Button")
        self.horizontalLayout_4.addWidget(self.ch4Button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mem1Button.setText(_translate("Dialog", "I"))
        self.mem2Button.setText(_translate("Dialog", "II"))
        self.mem3Button.setText(_translate("Dialog", "III"))
        self.mem11Label.setText(_translate("Dialog", "110min"))
        self.mem12Label.setText(_translate("Dialog", "11.75Hz - 100%"))
        self.mem13Label.setText(_translate("Dialog", "Sinusoidal"))
        self.mem21Label.setText(_translate("Dialog", "110min"))
        self.mem22Label.setText(_translate("Dialog", "11.75Hz - 100%"))
        self.mem23Label.setText(_translate("Dialog", "Sinusoidal"))
        self.mem31Label.setText(_translate("Dialog", "110min"))
        self.mem32Label.setText(_translate("Dialog", "11.75Hz - 100%"))
        self.mem33Label.setText(_translate("Dialog", "Sinusoidal"))
        self.minutesLabel.setText(_translate("Dialog", "120"))
        self.powerLabel.setText(_translate("Dialog", "100"))
        self.date_timeLabel.setText(_translate("Dialog", "19/03/2020 - 17:45"))
        self.ch1Button.setText(_translate("Dialog", "CH1"))
        self.ch2Button.setText(_translate("Dialog", "CH2"))
        self.ch3Button.setText(_translate("Dialog", "CH3"))
        self.ch4Button.setText(_translate("Dialog", "CH4"))

import magnet3_res_rc
