# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stretcher_rtc_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RtcDialog(object):
    def setupUi(self, RtcDialog):
        RtcDialog.setObjectName("RtcDialog")
        RtcDialog.resize(431, 322)
        RtcDialog.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(RtcDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 412, 304))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dayButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dayButton.setMinimumSize(QtCore.QSize(20, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.dayButton.setFont(font)
        self.dayButton.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"border: 0px")
        self.dayButton.setObjectName("dayButton")
        self.horizontalLayout_3.addWidget(self.dayButton)
        self.monthButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.monthButton.setMinimumSize(QtCore.QSize(20, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.monthButton.setFont(font)
        self.monthButton.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"border: 0px")
        self.monthButton.setObjectName("monthButton")
        self.horizontalLayout_3.addWidget(self.monthButton)
        self.yearButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.yearButton.setMinimumSize(QtCore.QSize(20, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.yearButton.setFont(font)
        self.yearButton.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"border: 0px")
        self.yearButton.setObjectName("yearButton")
        self.horizontalLayout_3.addWidget(self.yearButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hourButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.hourButton.setMinimumSize(QtCore.QSize(20, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.hourButton.setFont(font)
        self.hourButton.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"border: 0px")
        self.hourButton.setObjectName("hourButton")
        self.horizontalLayout_2.addWidget(self.hourButton)
        self.minuteButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.minuteButton.setMinimumSize(QtCore.QSize(20, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.minuteButton.setFont(font)
        self.minuteButton.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"border: 0px")
        self.minuteButton.setObjectName("minuteButton")
        self.horizontalLayout_2.addWidget(self.minuteButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.UpButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.UpButton.setMinimumSize(QtCore.QSize(100, 100))
        self.UpButton.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.UpButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/resources/Arriba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpButton.setIcon(icon)
        self.UpButton.setIconSize(QtCore.QSize(75, 75))
        self.UpButton.setObjectName("UpButton")
        self.verticalLayout_2.addWidget(self.UpButton)
        self.DwnButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.DwnButton.setMinimumSize(QtCore.QSize(100, 100))
        self.DwnButton.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.DwnButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/resources/Abajo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DwnButton.setIcon(icon1)
        self.DwnButton.setIconSize(QtCore.QSize(75, 75))
        self.DwnButton.setObjectName("DwnButton")
        self.verticalLayout_2.addWidget(self.DwnButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.doneButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneButton.sizePolicy().hasHeightForWidth())
        self.doneButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.doneButton.setFont(font)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout_5.addWidget(self.doneButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(RtcDialog)
        QtCore.QMetaObject.connectSlotsByName(RtcDialog)

    def retranslateUi(self, RtcDialog):
        _translate = QtCore.QCoreApplication.translate
        RtcDialog.setWindowTitle(_translate("RtcDialog", "Dialog"))
        self.label_2.setText(_translate("RtcDialog", "Date DD/MM/YY"))
        self.dayButton.setText(_translate("RtcDialog", "10"))
        self.monthButton.setText(_translate("RtcDialog", "10"))
        self.yearButton.setText(_translate("RtcDialog", "10"))
        self.label.setText(_translate("RtcDialog", "Hour HH:MM"))
        self.hourButton.setText(_translate("RtcDialog", "10"))
        self.minuteButton.setText(_translate("RtcDialog", "10"))
        self.doneButton.setText(_translate("RtcDialog", "Done!"))

import stretcher3_res_rc
