# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'micro2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1921, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(17, 17, 17);\n"
"border-radius: 12px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statusFrame = QtWidgets.QFrame(self.frame)
        self.statusFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.statusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusFrame.setObjectName("statusFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.statusFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.statusFrame)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(1669, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.mainsButton = QtWidgets.QPushButton(self.statusFrame)
        self.mainsButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mainsButton.setFont(font)
        self.mainsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mainsButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.mainsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/mains_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainsButton.setIcon(icon)
        self.mainsButton.setIconSize(QtCore.QSize(100, 100))
        self.mainsButton.setObjectName("mainsButton")
        self.horizontalLayout_2.addWidget(self.mainsButton)
        self.battaButton_3 = QtWidgets.QPushButton(self.statusFrame)
        self.battaButton_3.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battaButton_3.setFont(font)
        self.battaButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.battaButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.battaButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/batt_4_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.battaButton_3.setIcon(icon1)
        self.battaButton_3.setIconSize(QtCore.QSize(100, 100))
        self.battaButton_3.setObjectName("battaButton_3")
        self.horizontalLayout_2.addWidget(self.battaButton_3)
        self.battaButton_2 = QtWidgets.QPushButton(self.statusFrame)
        self.battaButton_2.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battaButton_2.setFont(font)
        self.battaButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.battaButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.battaButton_2.setText("")
        self.battaButton_2.setIcon(icon1)
        self.battaButton_2.setIconSize(QtCore.QSize(100, 100))
        self.battaButton_2.setObjectName("battaButton_2")
        self.horizontalLayout_2.addWidget(self.battaButton_2)
        self.battaButton = QtWidgets.QPushButton(self.statusFrame)
        self.battaButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battaButton.setFont(font)
        self.battaButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.battaButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.battaButton.setText("")
        self.battaButton.setIcon(icon1)
        self.battaButton.setIconSize(QtCore.QSize(100, 100))
        self.battaButton.setObjectName("battaButton")
        self.horizontalLayout_2.addWidget(self.battaButton)
        self.battbButton = QtWidgets.QPushButton(self.statusFrame)
        self.battbButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battbButton.setFont(font)
        self.battbButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.battbButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.battbButton.setText("")
        self.battbButton.setIcon(icon1)
        self.battbButton.setIconSize(QtCore.QSize(100, 100))
        self.battbButton.setObjectName("battbButton")
        self.horizontalLayout_2.addWidget(self.battbButton)
        self.bt_menu_open = QtWidgets.QPushButton(self.statusFrame)
        self.bt_menu_open.setMinimumSize(QtCore.QSize(100, 0))
        self.bt_menu_open.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.bt_menu_open.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/go-previous-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu_open.setIcon(icon2)
        self.bt_menu_open.setIconSize(QtCore.QSize(50, 50))
        self.bt_menu_open.setObjectName("bt_menu_open")
        self.horizontalLayout_2.addWidget(self.bt_menu_open)
        self.bt_menu_close = QtWidgets.QPushButton(self.statusFrame)
        self.bt_menu_close.setMinimumSize(QtCore.QSize(100, 0))
        self.bt_menu_close.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.bt_menu_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/go-next-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu_close.setIcon(icon3)
        self.bt_menu_close.setIconSize(QtCore.QSize(50, 50))
        self.bt_menu_close.setObjectName("bt_menu_close")
        self.horizontalLayout_2.addWidget(self.bt_menu_close)
        self.verticalLayout_2.addWidget(self.statusFrame)
        self.channelsFrame = QtWidgets.QFrame(self.frame)
        self.channelsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.channelsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.channelsFrame.setObjectName("channelsFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.channelsFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.channelsFrame)
        self.frame_2.setStyleSheet("background-color: rgb(129, 129, 129);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setGeometry(QtCore.QRect(1080, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.ch1_pwrLabel = QtWidgets.QLabel(self.groupBox_4)
        self.ch1_pwrLabel.setGeometry(QtCore.QRect(14, 27, 161, 81))
        self.ch1_pwrLabel.setMinimumSize(QtCore.QSize(130, 80))
        self.ch1_pwrLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Liberation Sans\";")
        self.ch1_pwrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_pwrLabel.setObjectName("ch1_pwrLabel")
        self.ch1_pwrDwnButton = QtWidgets.QPushButton(self.groupBox_4)
        self.ch1_pwrDwnButton.setGeometry(QtCore.QRect(10, 124, 81, 60))
        self.ch1_pwrDwnButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_pwrDwnButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_pwrDwnButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/go-down-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ch1_pwrDwnButton.setIcon(icon4)
        self.ch1_pwrDwnButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_pwrDwnButton.setObjectName("ch1_pwrDwnButton")
        self.ch1_pwrUpButton = QtWidgets.QPushButton(self.groupBox_4)
        self.ch1_pwrUpButton.setGeometry(QtCore.QRect(100, 125, 81, 60))
        self.ch1_pwrUpButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_pwrUpButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_pwrUpButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/go-up-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ch1_pwrUpButton.setIcon(icon5)
        self.ch1_pwrUpButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_pwrUpButton.setObjectName("ch1_pwrUpButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setGeometry(QtCore.QRect(865, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.ch1_freqLabel = QtWidgets.QLabel(self.groupBox_5)
        self.ch1_freqLabel.setGeometry(QtCore.QRect(14, 27, 161, 81))
        self.ch1_freqLabel.setMinimumSize(QtCore.QSize(130, 80))
        self.ch1_freqLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Liberation Sans\";")
        self.ch1_freqLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_freqLabel.setObjectName("ch1_freqLabel")
        self.ch1_freqDwnButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ch1_freqDwnButton.setGeometry(QtCore.QRect(10, 124, 81, 60))
        self.ch1_freqDwnButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_freqDwnButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_freqDwnButton.setText("")
        self.ch1_freqDwnButton.setIcon(icon4)
        self.ch1_freqDwnButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_freqDwnButton.setObjectName("ch1_freqDwnButton")
        self.ch1_freqUpButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ch1_freqUpButton.setGeometry(QtCore.QRect(100, 125, 81, 60))
        self.ch1_freqUpButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_freqUpButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_freqUpButton.setText("")
        self.ch1_freqUpButton.setIcon(icon5)
        self.ch1_freqUpButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_freqUpButton.setObjectName("ch1_freqUpButton")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setGeometry(QtCore.QRect(650, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.ch1_timerLabel = QtWidgets.QLabel(self.groupBox_6)
        self.ch1_timerLabel.setGeometry(QtCore.QRect(19, 27, 156, 81))
        self.ch1_timerLabel.setMinimumSize(QtCore.QSize(130, 80))
        self.ch1_timerLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Liberation Sans\";")
        self.ch1_timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_timerLabel.setObjectName("ch1_timerLabel")
        self.ch1_timerDwnButton = QtWidgets.QPushButton(self.groupBox_6)
        self.ch1_timerDwnButton.setGeometry(QtCore.QRect(10, 124, 81, 60))
        self.ch1_timerDwnButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_timerDwnButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_timerDwnButton.setText("")
        self.ch1_timerDwnButton.setIcon(icon4)
        self.ch1_timerDwnButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_timerDwnButton.setObjectName("ch1_timerDwnButton")
        self.ch1_timerUpButton = QtWidgets.QPushButton(self.groupBox_6)
        self.ch1_timerUpButton.setGeometry(QtCore.QRect(100, 125, 81, 60))
        self.ch1_timerUpButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_timerUpButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_timerUpButton.setText("")
        self.ch1_timerUpButton.setIcon(icon5)
        self.ch1_timerUpButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_timerUpButton.setObjectName("ch1_timerUpButton")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_7.setGeometry(QtCore.QRect(435, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.ch1_posButton = QtWidgets.QPushButton(self.groupBox_7)
        self.ch1_posButton.setGeometry(QtCore.QRect(20, 45, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton.setFont(font)
        self.ch1_posButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.ch1_posButton.setObjectName("ch1_posButton")
        self.ch1_altButton = QtWidgets.QPushButton(self.groupBox_7)
        self.ch1_altButton.setGeometry(QtCore.QRect(20, 95, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_altButton.setFont(font)
        self.ch1_altButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_altButton.setObjectName("ch1_altButton")
        self.ch1_negButton = QtWidgets.QPushButton(self.groupBox_7)
        self.ch1_negButton.setGeometry(QtCore.QRect(20, 145, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_negButton.setFont(font)
        self.ch1_negButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_negButton.setObjectName("ch1_negButton")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 25, 391, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.ch1_displayLabel = QtWidgets.QLabel(self.groupBox_8)
        self.ch1_displayLabel.setGeometry(QtCore.QRect(5, 25, 181, 161))
        self.ch1_displayLabel.setStyleSheet("background-color: rgb(157, 205, 255);\n"
"font: 75 65pt \"Liberation Sans\";")
        self.ch1_displayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_displayLabel.setObjectName("ch1_displayLabel")
        self.ch1_gainLabel = QtWidgets.QLabel(self.groupBox_8)
        self.ch1_gainLabel.setGeometry(QtCore.QRect(225, 35, 130, 81))
        self.ch1_gainLabel.setMinimumSize(QtCore.QSize(130, 80))
        self.ch1_gainLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Liberation Sans\";")
        self.ch1_gainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_gainLabel.setObjectName("ch1_gainLabel")
        self.ch1_gainDwnButton = QtWidgets.QPushButton(self.groupBox_8)
        self.ch1_gainDwnButton.setGeometry(QtCore.QRect(205, 125, 81, 60))
        self.ch1_gainDwnButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_gainDwnButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_gainDwnButton.setText("")
        self.ch1_gainDwnButton.setIcon(icon4)
        self.ch1_gainDwnButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_gainDwnButton.setObjectName("ch1_gainDwnButton")
        self.ch1_gainUpButton = QtWidgets.QPushButton(self.groupBox_8)
        self.ch1_gainUpButton.setGeometry(QtCore.QRect(295, 125, 81, 60))
        self.ch1_gainUpButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch1_gainUpButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_gainUpButton.setText("")
        self.ch1_gainUpButton.setIcon(icon5)
        self.ch1_gainUpButton.setIconSize(QtCore.QSize(50, 50))
        self.ch1_gainUpButton.setObjectName("ch1_gainUpButton")
        self.ch1_displayTextLabel = QtWidgets.QLabel(self.groupBox_8)
        self.ch1_displayTextLabel.setGeometry(QtCore.QRect(15, 30, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_displayTextLabel.setFont(font)
        self.ch1_displayTextLabel.setStyleSheet("background-color: rgb(157, 205, 255);\n"
"color: rgb(85, 170, 255);")
        self.ch1_displayTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_displayTextLabel.setObjectName("ch1_displayTextLabel")
        self.ch1_startButton = QtWidgets.QPushButton(self.frame_2)
        self.ch1_startButton.setGeometry(QtCore.QRect(1300, 50, 101, 156))
        self.ch1_startButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_startButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/pan-start-symbolic-rtl.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ch1_startButton.setIcon(icon6)
        self.ch1_startButton.setIconSize(QtCore.QSize(32, 32))
        self.ch1_startButton.setObjectName("ch1_startButton")
        self.ch1_stopButton = QtWidgets.QPushButton(self.frame_2)
        self.ch1_stopButton.setGeometry(QtCore.QRect(1300, 130, 101, 76))
        self.ch1_stopButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch1_stopButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/media-playback-stop-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ch1_stopButton.setIcon(icon7)
        self.ch1_stopButton.setIconSize(QtCore.QSize(32, 32))
        self.ch1_stopButton.setObjectName("ch1_stopButton")
        self.ch1_remainMinsLabel = QtWidgets.QLabel(self.frame_2)
        self.ch1_remainMinsLabel.setGeometry(QtCore.QRect(1285, 50, 81, 76))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_remainMinsLabel.setFont(font)
        self.ch1_remainMinsLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ch1_remainMinsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ch1_remainMinsLabel.setObjectName("ch1_remainMinsLabel")
        self.ch1_remainSecsLabel = QtWidgets.QLabel(self.frame_2)
        self.ch1_remainSecsLabel.setGeometry(QtCore.QRect(1370, 55, 96, 71))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_remainSecsLabel.setFont(font)
        self.ch1_remainSecsLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ch1_remainSecsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ch1_remainSecsLabel.setObjectName("ch1_remainSecsLabel")
        self.groupBox_28 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_28.setGeometry(QtCore.QRect(1440, 120, 381, 96))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_28.setFont(font)
        self.groupBox_28.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_28.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_28.setObjectName("groupBox_28")
        self.ch1_probeLabel = QtWidgets.QLabel(self.groupBox_28)
        self.ch1_probeLabel.setGeometry(QtCore.QRect(20, 35, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_probeLabel.setFont(font)
        self.ch1_probeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_probeLabel.setObjectName("ch1_probeLabel")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.channelsFrame)
        self.frame_4.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox_16 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_16.setGeometry(QtCore.QRect(15, 25, 196, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_16.setObjectName("groupBox_16")
        self.ch3_displayLabel = QtWidgets.QLabel(self.groupBox_16)
        self.ch3_displayLabel.setGeometry(QtCore.QRect(5, 25, 181, 161))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.ch3_displayLabel.setFont(font)
        self.ch3_displayLabel.setStyleSheet("background-color: rgb(157, 205, 255);\n"
"font: 75 60pt \"Liberation Sans\";")
        self.ch3_displayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_displayLabel.setObjectName("ch3_displayLabel")
        self.ch3_displayTextLabel = QtWidgets.QLabel(self.groupBox_16)
        self.ch3_displayTextLabel.setGeometry(QtCore.QRect(15, 25, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_displayTextLabel.setFont(font)
        self.ch3_displayTextLabel.setStyleSheet("background-color: rgb(157, 205, 255);\n"
"color: rgb(85, 170, 255);")
        self.ch3_displayTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_displayTextLabel.setObjectName("ch3_displayTextLabel")
        self.groupBox_17 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_17.setGeometry(QtCore.QRect(235, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_17.setObjectName("groupBox_17")
        self.ch3_posButton = QtWidgets.QPushButton(self.groupBox_17)
        self.ch3_posButton.setGeometry(QtCore.QRect(20, 45, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_posButton.setFont(font)
        self.ch3_posButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch3_posButton.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.ch3_posButton.setObjectName("ch3_posButton")
        self.ch3_altButton = QtWidgets.QPushButton(self.groupBox_17)
        self.ch3_altButton.setGeometry(QtCore.QRect(20, 95, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_altButton.setFont(font)
        self.ch3_altButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch3_altButton.setObjectName("ch3_altButton")
        self.ch3_negButton = QtWidgets.QPushButton(self.groupBox_17)
        self.ch3_negButton.setGeometry(QtCore.QRect(20, 145, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_negButton.setFont(font)
        self.ch3_negButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch3_negButton.setObjectName("ch3_negButton")
        self.groupBox_18 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_18.setGeometry(QtCore.QRect(660, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_18.setObjectName("groupBox_18")
        self.ch3_freqLabel = QtWidgets.QLabel(self.groupBox_18)
        self.ch3_freqLabel.setGeometry(QtCore.QRect(14, 27, 161, 81))
        self.ch3_freqLabel.setMinimumSize(QtCore.QSize(130, 80))
        self.ch3_freqLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Liberation Sans\";")
        self.ch3_freqLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_freqLabel.setObjectName("ch3_freqLabel")
        self.ch3_freqDwnButton = QtWidgets.QPushButton(self.groupBox_18)
        self.ch3_freqDwnButton.setGeometry(QtCore.QRect(10, 124, 81, 60))
        self.ch3_freqDwnButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch3_freqDwnButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_freqDwnButton.setText("")
        self.ch3_freqDwnButton.setIcon(icon4)
        self.ch3_freqDwnButton.setIconSize(QtCore.QSize(50, 50))
        self.ch3_freqDwnButton.setObjectName("ch3_freqDwnButton")
        self.ch3_freqUpButton = QtWidgets.QPushButton(self.groupBox_18)
        self.ch3_freqUpButton.setGeometry(QtCore.QRect(100, 125, 81, 60))
        self.ch3_freqUpButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch3_freqUpButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_freqUpButton.setText("")
        self.ch3_freqUpButton.setIcon(icon5)
        self.ch3_freqUpButton.setIconSize(QtCore.QSize(50, 50))
        self.ch3_freqUpButton.setObjectName("ch3_freqUpButton")
        self.groupBox_19 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_19.setGeometry(QtCore.QRect(445, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_19.setObjectName("groupBox_19")
        self.ch3_timerLabel = QtWidgets.QLabel(self.groupBox_19)
        self.ch3_timerLabel.setGeometry(QtCore.QRect(19, 27, 156, 81))
        self.ch3_timerLabel.setMinimumSize(QtCore.QSize(130, 80))
        self.ch3_timerLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Liberation Sans\";")
        self.ch3_timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_timerLabel.setObjectName("ch3_timerLabel")
        self.ch3_timerDwnButton = QtWidgets.QPushButton(self.groupBox_19)
        self.ch3_timerDwnButton.setGeometry(QtCore.QRect(10, 124, 81, 60))
        self.ch3_timerDwnButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch3_timerDwnButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_timerDwnButton.setText("")
        self.ch3_timerDwnButton.setIcon(icon4)
        self.ch3_timerDwnButton.setIconSize(QtCore.QSize(50, 50))
        self.ch3_timerDwnButton.setObjectName("ch3_timerDwnButton")
        self.ch3_timerUpButton = QtWidgets.QPushButton(self.groupBox_19)
        self.ch3_timerUpButton.setGeometry(QtCore.QRect(100, 125, 81, 60))
        self.ch3_timerUpButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch3_timerUpButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_timerUpButton.setText("")
        self.ch3_timerUpButton.setIcon(icon5)
        self.ch3_timerUpButton.setIconSize(QtCore.QSize(50, 50))
        self.ch3_timerUpButton.setObjectName("ch3_timerUpButton")
        self.ch3_startButton = QtWidgets.QPushButton(self.frame_4)
        self.ch3_startButton.setGeometry(QtCore.QRect(1095, 50, 101, 156))
        self.ch3_startButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_startButton.setText("")
        self.ch3_startButton.setIcon(icon6)
        self.ch3_startButton.setIconSize(QtCore.QSize(32, 32))
        self.ch3_startButton.setObjectName("ch3_startButton")
        self.groupBox_20 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_20.setGeometry(QtCore.QRect(875, 25, 191, 196))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_20.setObjectName("groupBox_20")
        self.ch3_pwrLabel = QtWidgets.QLabel(self.groupBox_20)
        self.ch3_pwrLabel.setGeometry(QtCore.QRect(14, 27, 161, 81))
        self.ch3_pwrLabel.setMinimumSize(QtCore.QSize(130, 80))
        self.ch3_pwrLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Liberation Sans\";")
        self.ch3_pwrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_pwrLabel.setObjectName("ch3_pwrLabel")
        self.ch3_pwrDwnButton = QtWidgets.QPushButton(self.groupBox_20)
        self.ch3_pwrDwnButton.setGeometry(QtCore.QRect(10, 124, 81, 60))
        self.ch3_pwrDwnButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch3_pwrDwnButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_pwrDwnButton.setText("")
        self.ch3_pwrDwnButton.setIcon(icon4)
        self.ch3_pwrDwnButton.setIconSize(QtCore.QSize(50, 50))
        self.ch3_pwrDwnButton.setObjectName("ch3_pwrDwnButton")
        self.ch3_pwrUpButton = QtWidgets.QPushButton(self.groupBox_20)
        self.ch3_pwrUpButton.setGeometry(QtCore.QRect(100, 125, 81, 60))
        self.ch3_pwrUpButton.setMinimumSize(QtCore.QSize(60, 60))
        self.ch3_pwrUpButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_pwrUpButton.setText("")
        self.ch3_pwrUpButton.setIcon(icon5)
        self.ch3_pwrUpButton.setIconSize(QtCore.QSize(50, 50))
        self.ch3_pwrUpButton.setObjectName("ch3_pwrUpButton")
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_21.setGeometry(QtCore.QRect(1440, 115, 381, 96))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_21.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_21.setObjectName("groupBox_21")
        self.ch3_probeLabel = QtWidgets.QLabel(self.groupBox_21)
        self.ch3_probeLabel.setGeometry(QtCore.QRect(20, 35, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_probeLabel.setFont(font)
        self.ch3_probeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_probeLabel.setObjectName("ch3_probeLabel")
        self.ch3_progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.ch3_progressBar.setGeometry(QtCore.QRect(1235, 60, 571, 36))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_progressBar.setFont(font)
        self.ch3_progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #2196F3;\n"
"    border-radius: 5px;\n"
"    background-color: #E0E0E0;\n"
"    text-align: right;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #2196F3;\n"
"    width: 10px; \n"
"    margin: 0.5px;\n"
"}")
        self.ch3_progressBar.setProperty("value", 24)
        self.ch3_progressBar.setObjectName("ch3_progressBar")
        self.ch3_remainMinsLabel = QtWidgets.QLabel(self.frame_4)
        self.ch3_remainMinsLabel.setGeometry(QtCore.QRect(1075, 50, 81, 76))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_remainMinsLabel.setFont(font)
        self.ch3_remainMinsLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ch3_remainMinsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ch3_remainMinsLabel.setObjectName("ch3_remainMinsLabel")
        self.ch3_stopButton = QtWidgets.QPushButton(self.frame_4)
        self.ch3_stopButton.setGeometry(QtCore.QRect(1095, 130, 101, 76))
        self.ch3_stopButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.ch3_stopButton.setText("")
        self.ch3_stopButton.setIcon(icon7)
        self.ch3_stopButton.setIconSize(QtCore.QSize(32, 32))
        self.ch3_stopButton.setObjectName("ch3_stopButton")
        self.ch3_remainSecsLabel = QtWidgets.QLabel(self.frame_4)
        self.ch3_remainSecsLabel.setGeometry(QtCore.QRect(1160, 55, 66, 71))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.ch3_remainSecsLabel.setFont(font)
        self.ch3_remainSecsLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ch3_remainSecsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ch3_remainSecsLabel.setObjectName("ch3_remainSecsLabel")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(30, 239, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.channelsFrame)
        self.frame_5.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.groupBox_26 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_26.setGeometry(QtCore.QRect(30, 30, 311, 241))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_26.setFont(font)
        self.groupBox_26.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_26.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_26.setObjectName("groupBox_26")
        self.intpButton = QtWidgets.QPushButton(self.groupBox_26)
        self.intpButton.setGeometry(QtCore.QRect(10, 60, 161, 131))
        self.intpButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.intpButton.setFont(font)
        self.intpButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intpButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.intpButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/resources/intel_pos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.intpButton.setIcon(icon8)
        self.intpButton.setIconSize(QtCore.QSize(100, 100))
        self.intpButton.setObjectName("intpButton")
        self.pch1dwnButton = QtWidgets.QPushButton(self.groupBox_26)
        self.pch1dwnButton.setGeometry(QtCore.QRect(190, 140, 104, 88))
        self.pch1dwnButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch1dwnButton.setFont(font)
        self.pch1dwnButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch1dwnButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch1dwnButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/resources/plates_no_conn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pch1dwnButton.setIcon(icon9)
        self.pch1dwnButton.setIconSize(QtCore.QSize(100, 100))
        self.pch1dwnButton.setObjectName("pch1dwnButton")
        self.pch1upButton = QtWidgets.QPushButton(self.groupBox_26)
        self.pch1upButton.setGeometry(QtCore.QRect(190, 40, 104, 88))
        self.pch1upButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch1upButton.setFont(font)
        self.pch1upButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch1upButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch1upButton.setText("")
        self.pch1upButton.setIcon(icon9)
        self.pch1upButton.setIconSize(QtCore.QSize(100, 100))
        self.pch1upButton.setObjectName("pch1upButton")
        self.groupBox_27 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_27.setGeometry(QtCore.QRect(370, 30, 141, 241))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_27.setFont(font)
        self.groupBox_27.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_27.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_27.setObjectName("groupBox_27")
        self.pch2dwnButton = QtWidgets.QPushButton(self.groupBox_27)
        self.pch2dwnButton.setGeometry(QtCore.QRect(20, 140, 104, 88))
        self.pch2dwnButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch2dwnButton.setFont(font)
        self.pch2dwnButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch2dwnButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch2dwnButton.setText("")
        self.pch2dwnButton.setIcon(icon9)
        self.pch2dwnButton.setIconSize(QtCore.QSize(100, 100))
        self.pch2dwnButton.setObjectName("pch2dwnButton")
        self.pch2upButton = QtWidgets.QPushButton(self.groupBox_27)
        self.pch2upButton.setGeometry(QtCore.QRect(20, 40, 104, 88))
        self.pch2upButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch2upButton.setFont(font)
        self.pch2upButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch2upButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch2upButton.setText("")
        self.pch2upButton.setIcon(icon9)
        self.pch2upButton.setIconSize(QtCore.QSize(100, 100))
        self.pch2upButton.setObjectName("pch2upButton")
        self.groupBox_29 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_29.setGeometry(QtCore.QRect(540, 30, 141, 241))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_29.setFont(font)
        self.groupBox_29.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_29.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_29.setObjectName("groupBox_29")
        self.pch3upButton = QtWidgets.QPushButton(self.groupBox_29)
        self.pch3upButton.setGeometry(QtCore.QRect(20, 40, 104, 88))
        self.pch3upButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch3upButton.setFont(font)
        self.pch3upButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch3upButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch3upButton.setText("")
        self.pch3upButton.setIcon(icon9)
        self.pch3upButton.setIconSize(QtCore.QSize(100, 100))
        self.pch3upButton.setObjectName("pch3upButton")
        self.pch3dwnButton = QtWidgets.QPushButton(self.groupBox_29)
        self.pch3dwnButton.setGeometry(QtCore.QRect(20, 140, 104, 88))
        self.pch3dwnButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch3dwnButton.setFont(font)
        self.pch3dwnButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch3dwnButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch3dwnButton.setText("")
        self.pch3dwnButton.setIcon(icon9)
        self.pch3dwnButton.setIconSize(QtCore.QSize(100, 100))
        self.pch3dwnButton.setObjectName("pch3dwnButton")
        self.groupBox_30 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_30.setGeometry(QtCore.QRect(710, 30, 141, 241))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_30.setFont(font)
        self.groupBox_30.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_30.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_30.setObjectName("groupBox_30")
        self.pch4dwnButton = QtWidgets.QPushButton(self.groupBox_30)
        self.pch4dwnButton.setGeometry(QtCore.QRect(20, 140, 104, 88))
        self.pch4dwnButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch4dwnButton.setFont(font)
        self.pch4dwnButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch4dwnButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch4dwnButton.setText("")
        self.pch4dwnButton.setIcon(icon9)
        self.pch4dwnButton.setIconSize(QtCore.QSize(100, 100))
        self.pch4dwnButton.setObjectName("pch4dwnButton")
        self.pch4upButton = QtWidgets.QPushButton(self.groupBox_30)
        self.pch4upButton.setGeometry(QtCore.QRect(20, 40, 104, 88))
        self.pch4upButton.setMinimumSize(QtCore.QSize(104, 88))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pch4upButton.setFont(font)
        self.pch4upButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pch4upButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.pch4upButton.setText("")
        self.pch4upButton.setIcon(icon9)
        self.pch4upButton.setIconSize(QtCore.QSize(100, 100))
        self.pch4upButton.setObjectName("pch4upButton")
        self.groupBox_31 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_31.setGeometry(QtCore.QRect(900, 60, 371, 211))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_31.setFont(font)
        self.groupBox_31.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_31.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_31.setObjectName("groupBox_31")
        self.platesPolUpButton = QtWidgets.QPushButton(self.groupBox_31)
        self.platesPolUpButton.setGeometry(QtCore.QRect(30, 60, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.platesPolUpButton.setFont(font)
        self.platesPolUpButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.platesPolUpButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.platesPolUpButton.setObjectName("platesPolUpButton")
        self.platesPolDwnButton = QtWidgets.QPushButton(self.groupBox_31)
        self.platesPolDwnButton.setGeometry(QtCore.QRect(30, 140, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.platesPolDwnButton.setFont(font)
        self.platesPolDwnButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.platesPolDwnButton.setStyleSheet("")
        self.platesPolDwnButton.setObjectName("platesPolDwnButton")
        self.groupBox_32 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_32.setGeometry(QtCore.QRect(1330, 60, 371, 211))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_32.setFont(font)
        self.groupBox_32.setStyleSheet("QGroupBox{\n"
"border: 2px solid red;\n"
"margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"background-color: rgb(129, 129, 129);\n"
"color: rgb(255, 255, 255);\n"
"/*subcontrol-origin: top right;*/\n"
"subcontrol-position: top center;\n"
"padding: 0 3px 0 3px;\n"
"top: -8px;\n"
"}")
        self.groupBox_32.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_32.setObjectName("groupBox_32")
        self.intelProbeDirButton = QtWidgets.QPushButton(self.groupBox_32)
        self.intelProbeDirButton.setGeometry(QtCore.QRect(30, 60, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.intelProbeDirButton.setFont(font)
        self.intelProbeDirButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intelProbeDirButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(129, 129, 129);\n"
"/*border: 2px solid red;*/\n"
"border: 2px solid rgb(218, 218, 218);\n"
"}\n"
"")
        self.intelProbeDirButton.setObjectName("intelProbeDirButton")
        self.intelProbeRevButton = QtWidgets.QPushButton(self.groupBox_32)
        self.intelProbeRevButton.setGeometry(QtCore.QRect(30, 140, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.intelProbeRevButton.setFont(font)
        self.intelProbeRevButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intelProbeRevButton.setStyleSheet("")
        self.intelProbeRevButton.setObjectName("intelProbeRevButton")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.lateralMenu = QtWidgets.QFrame(self.channelsFrame)
        self.lateralMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.lateralMenu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.lateralMenu.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.lateralMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lateralMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lateralMenu.setObjectName("lateralMenu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.lateralMenu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.lateralMenu)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.audioButton = QtWidgets.QPushButton(self.frame_7)
        self.audioButton.setMinimumSize(QtCore.QSize(0, 50))
        self.audioButton.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.audioButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/resources/audio-speakers-symbolic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioButton.setIcon(icon10)
        self.audioButton.setIconSize(QtCore.QSize(32, 32))
        self.audioButton.setObjectName("audioButton")
        self.verticalLayout_7.addWidget(self.audioButton)
        self.logButton = QtWidgets.QPushButton(self.frame_7)
        self.logButton.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.logButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/resources/view-paged-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logButton.setIcon(icon11)
        self.logButton.setIconSize(QtCore.QSize(50, 50))
        self.logButton.setObjectName("logButton")
        self.verticalLayout_7.addWidget(self.logButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.configButton = QtWidgets.QPushButton(self.frame_7)
        self.configButton.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.configButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/resources/system-run-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configButton.setIcon(icon12)
        self.configButton.setIconSize(QtCore.QSize(50, 50))
        self.configButton.setObjectName("configButton")
        self.verticalLayout_6.addWidget(self.configButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.pushButton_6.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/resources/insert-link-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon13)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.lateralMenu)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_audio = QtWidgets.QWidget()
        self.page_audio.setObjectName("page_audio")
        self.ch1_posButton_2 = QtWidgets.QPushButton(self.page_audio)
        self.ch1_posButton_2.setGeometry(QtCore.QRect(15, 50, 86, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton_2.setFont(font)
        self.ch1_posButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton_2.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.ch1_posButton_2.setObjectName("ch1_posButton_2")
        self.label = QtWidgets.QLabel(self.page_audio)
        self.label.setGeometry(QtCore.QRect(20, 10, 266, 26))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ch1_posButton_3 = QtWidgets.QPushButton(self.page_audio)
        self.ch1_posButton_3.setGeometry(QtCore.QRect(120, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton_3.setFont(font)
        self.ch1_posButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton_3.setStyleSheet("")
        self.ch1_posButton_3.setObjectName("ch1_posButton_3")
        self.ch1_posButton_4 = QtWidgets.QPushButton(self.page_audio)
        self.ch1_posButton_4.setGeometry(QtCore.QRect(225, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton_4.setFont(font)
        self.ch1_posButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton_4.setStyleSheet("")
        self.ch1_posButton_4.setObjectName("ch1_posButton_4")
        self.ch1_posButton_5 = QtWidgets.QPushButton(self.page_audio)
        self.ch1_posButton_5.setGeometry(QtCore.QRect(325, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton_5.setFont(font)
        self.ch1_posButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton_5.setStyleSheet("")
        self.ch1_posButton_5.setObjectName("ch1_posButton_5")
        self.label_2 = QtWidgets.QLabel(self.page_audio)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 246, 26))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.page_audio)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 160, 291, 36))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_5 = QtWidgets.QLabel(self.page_audio)
        self.label_5.setGeometry(QtCore.QRect(340, 165, 56, 26))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_audio)
        self.label_6.setGeometry(QtCore.QRect(20, 215, 266, 26))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ch1_posButton_6 = QtWidgets.QPushButton(self.page_audio)
        self.ch1_posButton_6.setGeometry(QtCore.QRect(20, 260, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton_6.setFont(font)
        self.ch1_posButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton_6.setStyleSheet("")
        self.ch1_posButton_6.setObjectName("ch1_posButton_6")
        self.ch1_posButton_7 = QtWidgets.QPushButton(self.page_audio)
        self.ch1_posButton_7.setGeometry(QtCore.QRect(20, 315, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton_7.setFont(font)
        self.ch1_posButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton_7.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.ch1_posButton_7.setObjectName("ch1_posButton_7")
        self.ch1_posButton_8 = QtWidgets.QPushButton(self.page_audio)
        self.ch1_posButton_8.setGeometry(QtCore.QRect(20, 370, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ch1_posButton_8.setFont(font)
        self.ch1_posButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ch1_posButton_8.setStyleSheet("")
        self.ch1_posButton_8.setObjectName("ch1_posButton_8")
        self.stackedWidget.addWidget(self.page_audio)
        self.page_log = QtWidgets.QWidget()
        self.page_log.setObjectName("page_log")
        self.textEdit = QtWidgets.QTextEdit(self.page_log)
        self.textEdit.setGeometry(QtCore.QRect(5, 45, 401, 651))
        self.textEdit.setObjectName("textEdit")
        self.label_7 = QtWidgets.QLabel(self.page_log)
        self.label_7.setGeometry(QtCore.QRect(5, 5, 286, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_log)
        self.page_config = QtWidgets.QWidget()
        self.page_config.setObjectName("page_config")
        self.label_8 = QtWidgets.QLabel(self.page_config)
        self.label_8.setGeometry(QtCore.QRect(10, 5, 356, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_51 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_51.setGeometry(QtCore.QRect(10, 70, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_51.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_52.setGeometry(QtCore.QRect(10, 145, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_52.setStyleSheet("")
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_53.setGeometry(QtCore.QRect(10, 310, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_53.setStyleSheet("")
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_54.setGeometry(QtCore.QRect(10, 235, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_54.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_55.setGeometry(QtCore.QRect(10, 475, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_55.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_56.setGeometry(QtCore.QRect(10, 400, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_56.setStyleSheet("")
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_57.setGeometry(QtCore.QRect(10, 640, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_57.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.page_config)
        self.pushButton_58.setGeometry(QtCore.QRect(10, 565, 396, 61))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_58.setStyleSheet("")
        self.pushButton_58.setObjectName("pushButton_58")
        self.stackedWidget.addWidget(self.page_config)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 8)
        self.horizontalLayout.addWidget(self.lateralMenu)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.channelsFrame)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 9)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Flowave"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Intensity"))
        self.ch1_pwrLabel.setText(_translate("MainWindow", "100uA"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Frequency"))
        self.ch1_freqLabel.setText(_translate("MainWindow", "100Hz"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Timer"))
        self.ch1_timerLabel.setText(_translate("MainWindow", "100s"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Polarity"))
        self.ch1_posButton.setText(_translate("MainWindow", "Positive"))
        self.ch1_altButton.setText(_translate("MainWindow", "Alternative"))
        self.ch1_negButton.setText(_translate("MainWindow", "Negative"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Gain Spectrum"))
        self.ch1_displayLabel.setText(_translate("MainWindow", "100"))
        self.ch1_gainLabel.setText(_translate("MainWindow", "100"))
        self.ch1_displayTextLabel.setText(_translate("MainWindow", "Offline Gain"))
        self.ch1_remainMinsLabel.setText(_translate("MainWindow", "22\'"))
        self.ch1_remainSecsLabel.setText(_translate("MainWindow", "22\'\'"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Channels Ready To Gen"))
        self.ch1_probeLabel.setText(_translate("MainWindow", "Normal Probe"))
        self.label_4.setText(_translate("MainWindow", "NervSync"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Gain"))
        self.ch3_displayLabel.setText(_translate("MainWindow", "1000"))
        self.ch3_displayTextLabel.setText(_translate("MainWindow", "Offline Gain"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Polarity"))
        self.ch3_posButton.setText(_translate("MainWindow", "Positive"))
        self.ch3_altButton.setText(_translate("MainWindow", "Alternative"))
        self.ch3_negButton.setText(_translate("MainWindow", "Negative"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Frequency"))
        self.ch3_freqLabel.setText(_translate("MainWindow", "100Hz"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Timer"))
        self.ch3_timerLabel.setText(_translate("MainWindow", "100s"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Intensity"))
        self.ch3_pwrLabel.setText(_translate("MainWindow", "100uA"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Channels Ready To Gen"))
        self.ch3_probeLabel.setText(_translate("MainWindow", "Normal Probe"))
        self.ch3_progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.ch3_remainMinsLabel.setText(_translate("MainWindow", "22\'"))
        self.ch3_remainSecsLabel.setText(_translate("MainWindow", "22\'\'"))
        self.label_3.setText(_translate("MainWindow", "CellSync"))
        self.groupBox_26.setTitle(_translate("MainWindow", "Ch1"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Ch2"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Ch3"))
        self.groupBox_30.setTitle(_translate("MainWindow", "Ch4"))
        self.groupBox_31.setTitle(_translate("MainWindow", "Plates Polarity"))
        self.platesPolUpButton.setText(_translate("MainWindow", "Positive Up"))
        self.platesPolDwnButton.setText(_translate("MainWindow", "Positive Down"))
        self.groupBox_32.setTitle(_translate("MainWindow", "Inteligent Probe Polarity"))
        self.intelProbeDirButton.setText(_translate("MainWindow", "Polarity Direct"))
        self.intelProbeRevButton.setText(_translate("MainWindow", "Polarity Reverse"))
        self.ch1_posButton_2.setText(_translate("MainWindow", "CH1"))
        self.label.setText(_translate("MainWindow", "Audio Output for channel:"))
        self.ch1_posButton_3.setText(_translate("MainWindow", "CH2"))
        self.ch1_posButton_4.setText(_translate("MainWindow", "CH3"))
        self.ch1_posButton_5.setText(_translate("MainWindow", "CH4"))
        self.label_2.setText(_translate("MainWindow", "Audio Volume:"))
        self.label_5.setText(_translate("MainWindow", "100%"))
        self.label_6.setText(_translate("MainWindow", "Audio options:"))
        self.ch1_posButton_6.setText(_translate("MainWindow", "Full audio"))
        self.ch1_posButton_7.setText(_translate("MainWindow", "Start Stop audio"))
        self.ch1_posButton_8.setText(_translate("MainWindow", "No audio"))
        self.label_7.setText(_translate("MainWindow", "System Log:"))
        self.label_8.setText(_translate("MainWindow", "Device Configurations:"))
        self.pushButton_51.setText(_translate("MainWindow", "CH1 Acuscope"))
        self.pushButton_52.setText(_translate("MainWindow", "CH1 Myopulse"))
        self.pushButton_53.setText(_translate("MainWindow", "CH2 Myopulse"))
        self.pushButton_54.setText(_translate("MainWindow", "CH2 Acuscope"))
        self.pushButton_55.setText(_translate("MainWindow", "CH3 Myopulse"))
        self.pushButton_56.setText(_translate("MainWindow", "CH3 Acuscope"))
        self.pushButton_57.setText(_translate("MainWindow", "CH4 Myopulse"))
        self.pushButton_58.setText(_translate("MainWindow", "CH4 Acuscope"))
import microc_res_rc
