# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'micro3_hamb.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(1920, 1080)
        MenuWindow.setStyleSheet("QMainWindow {\n"
"background-image: url(:/icons/resources/Screenshot.png);\n"
"}\n"
"/*background-color: rgba(255, 255, 255, 100);*/\n"
"")
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 13, 771, 1051))
        self.label.setStyleSheet("background-color: rgb(99, 82, 92);\n"
"border-radius: 25px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.ch1_startButton = QtWidgets.QPushButton(self.centralwidget)
        self.ch1_startButton.setGeometry(QtCore.QRect(30, 970, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.ch1_startButton.setFont(font)
        self.ch1_startButton.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.ch1_startButton.setObjectName("ch1_startButton")
        self.ch1_startButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ch1_startButton_2.setGeometry(QtCore.QRect(280, 970, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.ch1_startButton_2.setFont(font)
        self.ch1_startButton_2.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.ch1_startButton_2.setObjectName("ch1_startButton_2")
        self.conf3Button = QtWidgets.QPushButton(self.centralwidget)
        self.conf3Button.setGeometry(QtCore.QRect(530, 970, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.conf3Button.setFont(font)
        self.conf3Button.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.conf3Button.setObjectName("conf3Button")
        self.ch1_pwrLabel = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel.setGeometry(QtCore.QRect(30, 50, 251, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(28)
        self.ch1_pwrLabel.setFont(font)
        self.ch1_pwrLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ch1_pwrLabel.setObjectName("ch1_pwrLabel")
        self.audioSlider = QtWidgets.QSlider(self.centralwidget)
        self.audioSlider.setGeometry(QtCore.QRect(30, 110, 421, 31))
        self.audioSlider.setStyleSheet("border-radius: 5px;\n"
"/*\n"
"QSlider::groove:horizontal { \n"
"    background-color: black;\n"
"    border: 0px solid #424242; \n"
"    height: 10px; \n"
"    border-radius: 4px;\n"
"}\n"
"*/\n"
"/*\n"
"QSlider::handle:horizontal { \n"
"    background-color: red; \n"
"    border: 2px solid red; \n"
"    width: 16px; \n"
"    height: 20px; \n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 10px;\n"
"}\n"
"*/")
        self.audioSlider.setMaximum(10)
        self.audioSlider.setSingleStep(1)
        self.audioSlider.setPageStep(1)
        self.audioSlider.setOrientation(QtCore.Qt.Horizontal)
        self.audioSlider.setObjectName("audioSlider")
        self.volumeLabel = QtWidgets.QLabel(self.centralwidget)
        self.volumeLabel.setGeometry(QtCore.QRect(480, 100, 101, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(28)
        self.volumeLabel.setFont(font)
        self.volumeLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.volumeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.volumeLabel.setObjectName("volumeLabel")
        self.ch1_pwrLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_3.setGeometry(QtCore.QRect(30, 180, 251, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(28)
        self.ch1_pwrLabel_3.setFont(font)
        self.ch1_pwrLabel_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ch1_pwrLabel_3.setObjectName("ch1_pwrLabel_3")
        self.datetimeButton = QtWidgets.QPushButton(self.centralwidget)
        self.datetimeButton.setGeometry(QtCore.QRect(530, 590, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.datetimeButton.setFont(font)
        self.datetimeButton.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.datetimeButton.setObjectName("datetimeButton")
        self.ch1_pwrLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_4.setGeometry(QtCore.QRect(30, 450, 251, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(28)
        self.ch1_pwrLabel_4.setFont(font)
        self.ch1_pwrLabel_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ch1_pwrLabel_4.setObjectName("ch1_pwrLabel_4")
        self.monthLabel = QtWidgets.QLabel(self.centralwidget)
        self.monthLabel.setGeometry(QtCore.QRect(40, 240, 181, 71))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(36)
        self.monthLabel.setFont(font)
        self.monthLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.monthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monthLabel.setObjectName("monthLabel")
        self.month_DwnButton = QtWidgets.QPushButton(self.centralwidget)
        self.month_DwnButton.setGeometry(QtCore.QRect(130, 310, 91, 71))
        self.month_DwnButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.month_DwnButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/flecha_abajo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.month_DwnButton.setIcon(icon)
        self.month_DwnButton.setIconSize(QtCore.QSize(50, 50))
        self.month_DwnButton.setObjectName("month_DwnButton")
        self.month_UpButton = QtWidgets.QPushButton(self.centralwidget)
        self.month_UpButton.setGeometry(QtCore.QRect(40, 310, 91, 71))
        self.month_UpButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.month_UpButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/flecha_arriba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.month_UpButton.setIcon(icon1)
        self.month_UpButton.setIconSize(QtCore.QSize(50, 50))
        self.month_UpButton.setObjectName("month_UpButton")
        self.day_DwnButton = QtWidgets.QPushButton(self.centralwidget)
        self.day_DwnButton.setGeometry(QtCore.QRect(320, 310, 91, 71))
        self.day_DwnButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.day_DwnButton.setText("")
        self.day_DwnButton.setIcon(icon)
        self.day_DwnButton.setIconSize(QtCore.QSize(50, 50))
        self.day_DwnButton.setObjectName("day_DwnButton")
        self.dayLabel = QtWidgets.QLabel(self.centralwidget)
        self.dayLabel.setGeometry(QtCore.QRect(230, 240, 181, 71))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(36)
        self.dayLabel.setFont(font)
        self.dayLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.dayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dayLabel.setObjectName("dayLabel")
        self.day_UpButton = QtWidgets.QPushButton(self.centralwidget)
        self.day_UpButton.setGeometry(QtCore.QRect(230, 310, 91, 71))
        self.day_UpButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.day_UpButton.setText("")
        self.day_UpButton.setIcon(icon1)
        self.day_UpButton.setIconSize(QtCore.QSize(50, 50))
        self.day_UpButton.setObjectName("day_UpButton")
        self.year_UpButton = QtWidgets.QPushButton(self.centralwidget)
        self.year_UpButton.setGeometry(QtCore.QRect(420, 310, 91, 71))
        self.year_UpButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.year_UpButton.setText("")
        self.year_UpButton.setIcon(icon1)
        self.year_UpButton.setIconSize(QtCore.QSize(50, 50))
        self.year_UpButton.setObjectName("year_UpButton")
        self.yearLabel = QtWidgets.QLabel(self.centralwidget)
        self.yearLabel.setGeometry(QtCore.QRect(420, 240, 181, 71))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(36)
        self.yearLabel.setFont(font)
        self.yearLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.yearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yearLabel.setObjectName("yearLabel")
        self.year_DwnButton = QtWidgets.QPushButton(self.centralwidget)
        self.year_DwnButton.setGeometry(QtCore.QRect(510, 310, 91, 71))
        self.year_DwnButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.year_DwnButton.setText("")
        self.year_DwnButton.setIcon(icon)
        self.year_DwnButton.setIconSize(QtCore.QSize(50, 50))
        self.year_DwnButton.setObjectName("year_DwnButton")
        self.ch1_pwrLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_5.setGeometry(QtCore.QRect(30, 390, 191, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(22)
        self.ch1_pwrLabel_5.setFont(font)
        self.ch1_pwrLabel_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_pwrLabel_5.setObjectName("ch1_pwrLabel_5")
        self.ch1_pwrLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_6.setGeometry(QtCore.QRect(220, 390, 191, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(22)
        self.ch1_pwrLabel_6.setFont(font)
        self.ch1_pwrLabel_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_pwrLabel_6.setObjectName("ch1_pwrLabel_6")
        self.ch1_pwrLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_7.setGeometry(QtCore.QRect(420, 390, 191, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(22)
        self.ch1_pwrLabel_7.setFont(font)
        self.ch1_pwrLabel_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_pwrLabel_7.setObjectName("ch1_pwrLabel_7")
        self.ch1_pwrLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_8.setGeometry(QtCore.QRect(30, 660, 191, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(22)
        self.ch1_pwrLabel_8.setFont(font)
        self.ch1_pwrLabel_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_pwrLabel_8.setObjectName("ch1_pwrLabel_8")
        self.hour_DwnButton = QtWidgets.QPushButton(self.centralwidget)
        self.hour_DwnButton.setGeometry(QtCore.QRect(130, 580, 91, 71))
        self.hour_DwnButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.hour_DwnButton.setText("")
        self.hour_DwnButton.setIcon(icon)
        self.hour_DwnButton.setIconSize(QtCore.QSize(50, 50))
        self.hour_DwnButton.setObjectName("hour_DwnButton")
        self.ch1_pwrLabel_9 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_9.setGeometry(QtCore.QRect(220, 660, 191, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(22)
        self.ch1_pwrLabel_9.setFont(font)
        self.ch1_pwrLabel_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_9.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_pwrLabel_9.setObjectName("ch1_pwrLabel_9")
        self.minute_UpButton = QtWidgets.QPushButton(self.centralwidget)
        self.minute_UpButton.setGeometry(QtCore.QRect(230, 580, 91, 71))
        self.minute_UpButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.minute_UpButton.setText("")
        self.minute_UpButton.setIcon(icon1)
        self.minute_UpButton.setIconSize(QtCore.QSize(50, 50))
        self.minute_UpButton.setObjectName("minute_UpButton")
        self.minuteLabel = QtWidgets.QLabel(self.centralwidget)
        self.minuteLabel.setGeometry(QtCore.QRect(230, 510, 181, 71))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(36)
        self.minuteLabel.setFont(font)
        self.minuteLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.minuteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.minuteLabel.setObjectName("minuteLabel")
        self.hourLabel = QtWidgets.QLabel(self.centralwidget)
        self.hourLabel.setGeometry(QtCore.QRect(40, 510, 181, 71))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(36)
        self.hourLabel.setFont(font)
        self.hourLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.hourLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hourLabel.setObjectName("hourLabel")
        self.minute_DwnButton = QtWidgets.QPushButton(self.centralwidget)
        self.minute_DwnButton.setGeometry(QtCore.QRect(320, 580, 91, 71))
        self.minute_DwnButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.minute_DwnButton.setText("")
        self.minute_DwnButton.setIcon(icon)
        self.minute_DwnButton.setIconSize(QtCore.QSize(50, 50))
        self.minute_DwnButton.setObjectName("minute_DwnButton")
        self.hour_UpButton = QtWidgets.QPushButton(self.centralwidget)
        self.hour_UpButton.setGeometry(QtCore.QRect(40, 580, 91, 71))
        self.hour_UpButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 0px")
        self.hour_UpButton.setText("")
        self.hour_UpButton.setIcon(icon1)
        self.hour_UpButton.setIconSize(QtCore.QSize(50, 50))
        self.hour_UpButton.setObjectName("hour_UpButton")
        MenuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "MainWindow"))
        self.ch1_startButton.setText(_translate("MenuWindow", "Config"))
        self.ch1_startButton_2.setText(_translate("MenuWindow", "Config"))
        self.conf3Button.setText(_translate("MenuWindow", "Done"))
        self.ch1_pwrLabel.setText(_translate("MenuWindow", "Audio Volume"))
        self.volumeLabel.setText(_translate("MenuWindow", "100%"))
        self.ch1_pwrLabel_3.setText(_translate("MenuWindow", "Change Date"))
        self.datetimeButton.setText(_translate("MenuWindow", "Update"))
        self.ch1_pwrLabel_4.setText(_translate("MenuWindow", "Change Time"))
        self.monthLabel.setText(_translate("MenuWindow", "12"))
        self.dayLabel.setText(_translate("MenuWindow", "20"))
        self.yearLabel.setText(_translate("MenuWindow", "2000"))
        self.ch1_pwrLabel_5.setText(_translate("MenuWindow", "Month"))
        self.ch1_pwrLabel_6.setText(_translate("MenuWindow", "Day"))
        self.ch1_pwrLabel_7.setText(_translate("MenuWindow", "Year"))
        self.ch1_pwrLabel_8.setText(_translate("MenuWindow", "Hour"))
        self.ch1_pwrLabel_9.setText(_translate("MenuWindow", "Minute"))
        self.minuteLabel.setText(_translate("MenuWindow", "20"))
        self.hourLabel.setText(_translate("MenuWindow", "12"))
import microc_res_rc
