# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'micro3_hamb.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(1920, 1080)
        MenuWindow.setStyleSheet("QMainWindow {\n"
"background-image: url(:/icons/resources/Screenshot.png);\n"
"}\n"
"/*background-color: rgba(255, 255, 255, 100);*/\n"
"")
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 13, 771, 1051))
        self.label.setStyleSheet("background-color: rgb(99, 82, 92);\n"
"border-radius: 25px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.ch1_startButton = QtWidgets.QPushButton(self.centralwidget)
        self.ch1_startButton.setGeometry(QtCore.QRect(30, 970, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.ch1_startButton.setFont(font)
        self.ch1_startButton.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.ch1_startButton.setObjectName("ch1_startButton")
        self.ch1_startButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ch1_startButton_2.setGeometry(QtCore.QRect(280, 970, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.ch1_startButton_2.setFont(font)
        self.ch1_startButton_2.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.ch1_startButton_2.setObjectName("ch1_startButton_2")
        self.conf3Button = QtWidgets.QPushButton(self.centralwidget)
        self.conf3Button.setGeometry(QtCore.QRect(530, 970, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.conf3Button.setFont(font)
        self.conf3Button.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.conf3Button.setObjectName("conf3Button")
        self.ch1_pwrLabel = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel.setGeometry(QtCore.QRect(30, 50, 251, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(28)
        self.ch1_pwrLabel.setFont(font)
        self.ch1_pwrLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ch1_pwrLabel.setObjectName("ch1_pwrLabel")
        self.audioSlider = QtWidgets.QSlider(self.centralwidget)
        self.audioSlider.setGeometry(QtCore.QRect(30, 110, 421, 31))
        self.audioSlider.setStyleSheet("border-radius: 5px;\n"
"/*\n"
"QSlider::groove:horizontal { \n"
"    background-color: black;\n"
"    border: 0px solid #424242; \n"
"    height: 10px; \n"
"    border-radius: 4px;\n"
"}\n"
"*/\n"
"/*\n"
"QSlider::handle:horizontal { \n"
"    background-color: red; \n"
"    border: 2px solid red; \n"
"    width: 16px; \n"
"    height: 20px; \n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 10px;\n"
"}\n"
"*/")
        self.audioSlider.setOrientation(QtCore.Qt.Horizontal)
        self.audioSlider.setObjectName("audioSlider")
        self.volumeLabel = QtWidgets.QLabel(self.centralwidget)
        self.volumeLabel.setGeometry(QtCore.QRect(480, 100, 101, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(28)
        self.volumeLabel.setFont(font)
        self.volumeLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.volumeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.volumeLabel.setObjectName("volumeLabel")
        self.ch1_pwrLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ch1_pwrLabel_3.setGeometry(QtCore.QRect(30, 180, 251, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(28)
        self.ch1_pwrLabel_3.setFont(font)
        self.ch1_pwrLabel_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(99, 82, 92);")
        self.ch1_pwrLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ch1_pwrLabel_3.setObjectName("ch1_pwrLabel_3")
        self.ch1_startButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.ch1_startButton_4.setGeometry(QtCore.QRect(30, 240, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.ch1_startButton_4.setFont(font)
        self.ch1_startButton_4.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.ch1_startButton_4.setObjectName("ch1_startButton_4")
        self.ch1_startButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.ch1_startButton_5.setGeometry(QtCore.QRect(280, 240, 231, 51))
        font = QtGui.QFont()
        font.setFamily("TT Norms ExtraLight")
        font.setPointSize(24)
        self.ch1_startButton_5.setFont(font)
        self.ch1_startButton_5.setStyleSheet("background-color: rgba(81, 70, 75, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px")
        self.ch1_startButton_5.setObjectName("ch1_startButton_5")
        MenuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "MainWindow"))
        self.ch1_startButton.setText(_translate("MenuWindow", "Config"))
        self.ch1_startButton_2.setText(_translate("MenuWindow", "Config"))
        self.conf3Button.setText(_translate("MenuWindow", "Done"))
        self.ch1_pwrLabel.setText(_translate("MenuWindow", "Audio Volume"))
        self.volumeLabel.setText(_translate("MenuWindow", "24%"))
        self.ch1_pwrLabel_3.setText(_translate("MenuWindow", "Audio Output"))
        self.ch1_startButton_4.setText(_translate("MenuWindow", "ON"))
        self.ch1_startButton_5.setText(_translate("MenuWindow", "OFF"))
import microc_res_rc
